import type { FieldDefinition } from './types'

const people = ['Neo Morake', 'Amara Dlamini', 'Lethabo Nkosi', 'Zanele Khumalo']

export const domainFields: Record<string, FieldDefinition[]> = {
  leads: [
    { name: 'name', label: 'Company / prospect', section: 'Lead information', required: true },
    { name: 'contact', label: 'Primary contact', section: 'Lead information', required: true },
    { name: 'email', label: 'Email', section: 'Lead information', type: 'email' },
    { name: 'phone', label: 'Phone', section: 'Lead information', type: 'tel' },
    { name: 'source', label: 'Lead source', section: 'Qualification', type: 'select', options: ['Referral', 'Website', 'Campaign', 'Event', 'Partner', 'Outbound'] },
    { name: 'value', label: 'Estimated value', section: 'Qualification', type: 'number' },
    { name: 'status', label: 'Qualification status', section: 'Qualification', type: 'select', options: ['New', 'Contacted', 'Qualified', 'Disqualified', 'Converted'] },
    { name: 'owner', label: 'Lead owner', section: 'Ownership', type: 'select', options: people },
    { name: 'notes', label: 'Qualification notes', section: 'Ownership', type: 'textarea' },
  ],
  quotes: [
    { name: 'name', label: 'Quote number', section: 'Quote information', required: true },
    { name: 'client', label: 'Client', section: 'Quote information', required: true },
    { name: 'contact', label: 'Client contact', section: 'Quote information' },
    { name: 'expiry', label: 'Valid until', section: 'Quote information', type: 'date' },
    { name: 'owner', label: 'Quote owner', section: 'Commercial ownership', type: 'select', options: people },
    { name: 'status', label: 'Status', section: 'Commercial ownership', type: 'select', options: ['Draft', 'Internal Review', 'Sent', 'Accepted', 'Declined', 'Expired'] },
    { name: 'total', label: 'Quote total', section: 'Commercial terms', type: 'number' },
    { name: 'terms', label: 'Terms and conditions', section: 'Commercial terms', type: 'textarea' },
  ],
  sales: [
    { name: 'name', label: 'Opportunity name', section: 'Opportunity', required: true },
    { name: 'client', label: 'Client / prospect', section: 'Opportunity', required: true },
    { name: 'value', label: 'Expected value', section: 'Opportunity', type: 'number' },
    { name: 'status', label: 'Pipeline stage', section: 'Opportunity', type: 'select', options: ['Discovery', 'Qualified', 'Proposal', 'Negotiation', 'Won', 'Lost'] },
    { name: 'probability', label: 'Probability (%)', section: 'Forecast', type: 'number' },
    { name: 'close', label: 'Expected close', section: 'Forecast', type: 'date' },
    { name: 'owner', label: 'Opportunity owner', section: 'Ownership', type: 'select', options: people },
    { name: 'nextStep', label: 'Next step', section: 'Ownership' },
    { name: 'notes', label: 'Commercial notes', section: 'Ownership', type: 'textarea' },
  ],
  invoices: [
    { name: 'name', label: 'Invoice number', section: 'Invoice information', required: true },
    { name: 'client', label: 'Client', section: 'Invoice information', required: true },
    { name: 'issueDate', label: 'Issue date', section: 'Invoice information', type: 'date' },
    { name: 'due', label: 'Due date', section: 'Invoice information', type: 'date' },
    { name: 'total', label: 'Invoice total', section: 'Amounts', type: 'number' },
    { name: 'balance', label: 'Outstanding balance', section: 'Amounts', type: 'number' },
    { name: 'status', label: 'Payment status', section: 'Amounts', type: 'select', options: ['Draft', 'Issued', 'Partially Paid', 'Paid', 'Overdue', 'Cancelled'] },
    { name: 'owner', label: 'Finance owner', section: 'Controls', type: 'select', options: people },
    { name: 'notes', label: 'Payment notes', section: 'Controls', type: 'textarea' },
  ],
  expenses: [
    { name: 'name', label: 'Expense description', section: 'Expense information', required: true },
    { name: 'category', label: 'Category', section: 'Expense information', type: 'select', options: ['Travel', 'Software', 'Professional Services', 'Office', 'Marketing', 'Other'] },
    { name: 'vendor', label: 'Vendor', section: 'Expense information' },
    { name: 'amount', label: 'Amount', section: 'Expense information', type: 'number', required: true },
    { name: 'date', label: 'Expense date', section: 'Allocation', type: 'date' },
    { name: 'project', label: 'Project', section: 'Allocation' },
    { name: 'client', label: 'Client', section: 'Allocation' },
    { name: 'owner', label: 'Submitted by', section: 'Approval', type: 'select', options: people },
    { name: 'status', label: 'Approval status', section: 'Approval', type: 'select', options: ['Draft', 'Submitted', 'Awaiting Approval', 'Approved', 'Rejected'] },
    { name: 'notes', label: 'Business purpose', section: 'Approval', type: 'textarea' },
  ],
  forecast: [
    { name: 'name', label: 'Scenario name', section: 'Scenario', required: true },
    { name: 'period', label: 'Forecast period', section: 'Scenario', required: true },
    { name: 'status', label: 'Scenario status', section: 'Scenario', type: 'select', options: ['Draft', 'Current', 'Approved', 'Archived'] },
    { name: 'owner', label: 'Scenario owner', section: 'Scenario', type: 'select', options: people },
    { name: 'actual', label: 'Actual value', section: 'Financial assumptions', type: 'number' },
    { name: 'projected', label: 'Projected value', section: 'Financial assumptions', type: 'number' },
    { name: 'confidence', label: 'Confidence (%)', section: 'Financial assumptions', type: 'number' },
    { name: 'notes', label: 'Assumptions and methodology', section: 'Financial assumptions', type: 'textarea' },
  ],
  team: [
    { name: 'name', label: 'Member name', section: 'Member information', required: true },
    { name: 'email', label: 'Work email', section: 'Member information', type: 'email', required: true },
    { name: 'title', label: 'Job title', section: 'Role & organisation', required: true },
    { name: 'department', label: 'Department', section: 'Role & organisation' },
    { name: 'team', label: 'Team', section: 'Role & organisation' },
    { name: 'role', label: 'Delivery role', section: 'Role & organisation' },
    { name: 'owner', label: 'Manager', section: 'Role & organisation', type: 'select', options: people },
    { name: 'capacity', label: 'Capacity allocation', section: 'Delivery context', type: 'number' },
    { name: 'availability', label: 'Availability', section: 'Delivery context', type: 'select', options: ['Available', 'Partial', 'Busy', 'Unavailable'] },
    { name: 'status', label: 'Account status', section: 'Access', type: 'select', options: ['Active', 'Invited', 'Inactive'] },
  ],
}
