import type { FieldDefinition, ModuleDefinition } from './types'

const commonFields: FieldDefinition[] = [
  { name: 'name', label: 'Name', section: 'Core information', required: true },
  { name: 'owner', label: 'Owner', section: 'Ownership', type: 'select', options: ['Neo Morake', 'Amara Dlamini', 'Lethabo Nkosi'] },
  { name: 'status', label: 'Status', section: 'Ownership', type: 'select', options: ['Active', 'Draft', 'On Track', 'At Risk', 'Archived'] },
  { name: 'notes', label: 'Notes', section: 'Additional information', type: 'textarea', placeholder: 'Add relevant context and internal notes' },
]

const definitions: ModuleDefinition[] = [
  { id: 'clients', label: 'Clients', singular: 'Client', description: 'Manage client relationships, engagements, health and account activity.', route: '/operations/clients', category: 'Operations', primaryAction: 'Add Client', archiveLabel: 'Archive Client', views: ['List', 'Grid'], filters: ['Status', 'Owner', 'Industry'], columns: ['Client', 'Primary Contact', 'Service / Engagement', 'Account Owner', 'Active Projects', 'Client Health', 'Status', 'Last Activity'], tabs: ['Overview', 'Projects', 'Tasks', 'Services', 'Onboarding', 'Documents', 'Contacts', 'Commercial', 'Activity'], fields: [
    { name: 'name', label: 'Company name', section: 'Company Information', required: true }, { name: 'industry', label: 'Industry', section: 'Company Information' }, { name: 'website', label: 'Website', section: 'Company Information' },
    { name: 'contact', label: 'Primary contact', section: 'Primary Contact', required: true }, { name: 'email', label: 'Email', section: 'Primary Contact', type: 'email' }, { name: 'phone', label: 'Phone', section: 'Primary Contact', type: 'tel' },
    { name: 'owner', label: 'Account owner', section: 'Account Ownership', type: 'select', options: ['Neo Morake', 'Amara Dlamini', 'Lethabo Nkosi'] }, { name: 'service', label: 'Primary engagement', section: 'Engagement Information' }, { name: 'billing', label: 'Billing contact', section: 'Billing Information', type: 'email' }, { name: 'notes', label: 'Notes', section: 'Notes', type: 'textarea' },
  ] },
  { id: 'projects', label: 'Projects', singular: 'Project', description: 'Coordinate delivery, milestones, teams, risks and client outcomes.', route: '/operations/projects', category: 'Operations', primaryAction: 'New Project', archiveLabel: 'Archive Project', views: ['List', 'Board', 'Timeline'], filters: ['Status', 'Client', 'Owner', 'Team', 'Due date', 'Risk'], columns: ['Project', 'Client', 'Owner', 'Progress', 'Next Milestone', 'Due Date', 'Risk', 'Status'], tabs: ['Overview', 'Timeline', 'Milestones', 'Deliverables', 'Tasks', 'Team', 'Documents', 'Risks', 'Approvals', 'Meetings', 'Activity', 'Atlas'], fields: [
    { name: 'name', label: 'Project name', section: 'Project Information', required: true }, { name: 'client', label: 'Client', section: 'Client', type: 'select', options: ['LGNDRY.CO', 'Growthpoint Properties', 'Pioneertown'] }, { name: 'owner', label: 'Project owner', section: 'Owner', type: 'select', options: ['Neo Morake', 'Amara Dlamini'] }, { name: 'team', label: 'Team', section: 'Team' }, { name: 'startDate', label: 'Start date', section: 'Dates', type: 'date' }, { name: 'dueDate', label: 'Due date', section: 'Dates', type: 'date' }, { name: 'scope', label: 'Scope', section: 'Scope', type: 'textarea' }, { name: 'budget', label: 'Budget', section: 'Budget', type: 'number' }, { name: 'priority', label: 'Priority', section: 'Priority', type: 'select', options: ['Low', 'Medium', 'High', 'Critical'] }, { name: 'status', label: 'Status', section: 'Status', type: 'select', options: ['Planning', 'On Track', 'At Risk', 'Delayed', 'Complete'] },
  ] },
  { id: 'tasks', label: 'Tasks', singular: 'Task', description: 'Prioritize work across people, clients and projects.', route: '/operations/tasks', category: 'Operations', primaryAction: 'Create Task', views: ['My Tasks', 'Team Tasks', 'All Tasks', 'Today', 'Upcoming', 'Overdue', 'Completed', 'Board'], filters: ['Assignee', 'Project', 'Client', 'Priority', 'Status', 'Due date'], columns: ['Task', 'Assignee', 'Project', 'Client', 'Priority', 'Due Date', 'Status'], tabs: ['Details', 'Subtasks', 'Dependencies', 'Activity'], compactCreate: true, fields: commonFields },
  { id: 'calendar', label: 'Calendar', singular: 'Event', description: 'See meetings, milestones, deadlines, leave and company events together.', route: '/operations/calendar', category: 'Operations', primaryAction: 'Create Event', views: ['Month', 'Week', 'Day', 'Agenda'], filters: ['Tasks', 'Meetings', 'Milestones', 'Deadlines', 'Events', 'Leave'], columns: ['Event', 'Source', 'Date', 'Time', 'Owner', 'Status'], tabs: ['Details', 'Attendees', 'Related Records', 'Activity'], compactCreate: true, fields: commonFields },
  { id: 'leads', label: 'Leads', singular: 'Lead', description: 'Qualify prospective organizations and convert the right opportunities.', route: '/commercial/leads', category: 'Commercial', primaryAction: 'Add Lead', archiveLabel: 'Archive Lead', views: ['All', 'New', 'Qualified', 'Disqualified', 'Converted'], filters: ['Status', 'Source', 'Owner', 'Value'], columns: ['Company', 'Contact', 'Source', 'Owner', 'Estimated Value', 'Status', 'Last Activity'], tabs: ['Overview', 'Activity', 'Communication', 'Qualification', 'Documents', 'Atlas'], fields: commonFields },
  { id: 'quotes', label: 'Quotes', singular: 'Quote', description: 'Prepare, review and track polished client quotations.', route: '/commercial/quotes', category: 'Commercial', primaryAction: 'New Quote', archiveLabel: 'Archive Quote', views: ['All', 'Draft', 'Internal Review', 'Sent', 'Accepted', 'Declined', 'Expired'], filters: ['Status', 'Client', 'Owner', 'Expiry'], columns: ['Quote', 'Client', 'Owner', 'Total', 'Expiry', 'Status', 'Last Activity'], tabs: ['Document', 'Line Items', 'Activity', 'Related Records'], fields: commonFields },
  { id: 'sales', label: 'Sales', singular: 'Opportunity', description: 'Manage pipeline, proposals, contracts, renewals and commercial forecasts.', route: '/commercial/sales', category: 'Commercial', primaryAction: 'New Opportunity', views: ['Pipeline', 'Opportunities', 'Proposals', 'Contracts', 'Renewals', 'Forecast'], filters: ['Stage', 'Owner', 'Value', 'Close date'], columns: ['Opportunity', 'Client / Prospect', 'Owner', 'Stage', 'Value', 'Probability', 'Expected Close'], tabs: ['Overview', 'Activity', 'Proposals', 'Contracts', 'Documents', 'Atlas'], fields: commonFields },
  { id: 'invoices', label: 'Invoices', singular: 'Invoice', description: 'Track operational billing, collections and payment status.', route: '/finance/invoices', category: 'Finance', primaryAction: 'New Invoice', archiveLabel: 'Archive Invoice', views: ['All', 'Draft', 'Issued', 'Partially Paid', 'Paid', 'Overdue', 'Cancelled'], filters: ['Status', 'Client', 'Issue date', 'Due date'], columns: ['Invoice', 'Client', 'Issue Date', 'Due Date', 'Total', 'Balance', 'Status'], tabs: ['Document', 'Payments', 'Activity', 'Related Records'], fields: commonFields },
  { id: 'expenses', label: 'Expenses', singular: 'Expense', description: 'Capture operational expenses and manage approval visibility.', route: '/finance/expenses', category: 'Finance', primaryAction: 'Add Expense', views: ['All', 'Submitted', 'Awaiting Approval', 'Approved', 'Rejected'], filters: ['Status', 'Category', 'Project', 'Client', 'Submitted by'], columns: ['Expense', 'Category', 'Vendor', 'Project', 'Submitted By', 'Amount', 'Date', 'Status'], tabs: ['Overview', 'Receipt', 'Approval', 'Activity'], fields: commonFields },
  { id: 'forecast', label: 'Forecast', singular: 'Scenario', description: 'Understand revenue, expenses, cash flow and budget direction.', route: '/finance/forecast', category: 'Finance', primaryAction: 'New Scenario', views: ['Revenue Forecast', 'Expense Forecast', 'Cash Flow', 'Budget vs Actual', 'Client Revenue', 'Project Revenue', 'Scenarios'], filters: ['Period', 'Scenario', 'Client', 'Project'], columns: ['Forecast', 'Period', 'Actual', 'Projected', 'Variance', 'Confidence', 'Status'], tabs: ['Overview', 'Assumptions', 'Revenue', 'Expenses', 'Activity'], fields: commonFields },
  { id: 'team', label: 'Team', singular: 'Employee', description: 'Explore the organization, people, teams and employment records.', route: '/people/team', category: 'People', primaryAction: 'Add Employee', archiveLabel: 'Deactivate Employee', views: ['Team Directory', 'Departments', 'Teams', 'Org Chart'], filters: ['Department', 'Team', 'Manager', 'Employment Type', 'Status'], columns: ['Employee', 'Job Title', 'Department', 'Team', 'Manager', 'Start Date', 'Status'], tabs: ['Overview', 'Role', 'Work', 'Goals', 'Performance', 'Leave', 'Documents', 'Equipment', 'Activity'], fields: commonFields },
  { id: 'hr', label: 'HR', singular: 'Candidate', description: 'Coordinate recruitment, onboarding, performance, learning and policies.', route: '/people/hr', category: 'People', primaryAction: 'Create Vacancy', views: ['Recruitment', 'Candidates', 'Onboarding', 'Performance', 'Learning', 'Policies', 'Offboarding'], filters: ['Stage', 'Department', 'Owner', 'Status'], columns: ['Record', 'Type', 'Department', 'Owner', 'Stage', 'Due Date', 'Status'], tabs: ['Overview', 'Candidates', 'Checklist', 'Documents', 'Activity'], fields: commonFields },
  { id: 'leave', label: 'Leave', singular: 'Leave Request', description: 'Coordinate requests, approvals, calendars and balances.', route: '/people/leave', category: 'People', primaryAction: 'Request Leave', views: ['My Leave', 'Team Leave', 'Requests', 'Approvals', 'Calendar', 'Balances'], filters: ['Status', 'Leave type', 'Employee', 'Date'], columns: ['Employee', 'Leave Type', 'From', 'To', 'Days', 'Approver', 'Status'], tabs: ['Overview', 'Approval', 'Balance Impact', 'Activity'], compactCreate: true, fields: commonFields },
  { id: 'knowledge', label: 'Knowledge', singular: 'Article', description: 'Capture organizational knowledge, SOPs, policies and decisions.', route: '/knowledge', category: 'Knowledge', primaryAction: 'New Article', archiveLabel: 'Archive Article', views: ['Knowledge Home', 'Company Knowledge', 'Client Knowledge', 'Project Knowledge', 'Documents', 'SOPs', 'Policies', 'Templates', 'Meeting Notes', 'Decision Register', 'Archive'], filters: ['Category', 'Owner', 'Visibility', 'Status'], columns: ['Title', 'Category', 'Owner', 'Related Record', 'Visibility', 'Status', 'Updated'], tabs: ['Article', 'Related Records', 'Versions', 'Activity', 'Atlas'], fields: commonFields },
  { id: 'atlas', label: 'Atlas', singular: 'Insight', description: 'Explore intelligence, recommendations, reports and organizational memory.', route: '/atlas', category: 'Atlas', primaryAction: 'Ask Atlas', views: ['Ask Atlas', 'Insights', 'Recommendations', 'Reports', 'Business Intelligence', 'Process Intelligence', 'Client Intelligence', 'Project Intelligence', 'Knowledge Search', 'Memory'], filters: ['Type', 'Module', 'Priority', 'Status'], columns: ['Insight', 'Type', 'Module', 'Priority', 'Confidence', 'Status', 'Generated'], tabs: ['Overview', 'Sources', 'Related Records', 'Activity'], compactCreate: true, fields: commonFields },
  { id: 'settings', label: 'Settings', singular: 'Setting', description: 'Configure HIMARK, people, modules, integrations and governance.', route: '/settings', category: 'Administration', primaryAction: 'Save Changes', views: ['Company', 'Users', 'Teams', 'Roles & Permissions', 'Modules', 'Integrations', 'Notifications', 'Templates', 'Custom Fields', 'Appearance', 'Security', 'Audit Log', 'Data'], filters: ['Area', 'Status', 'Owner'], columns: ['Setting', 'Area', 'Owner', 'Last Changed', 'Status'], tabs: ['Overview', 'Activity'], fields: commonFields },
]

export const productModules = definitions
export const moduleById = Object.fromEntries(definitions.map((definition) => [definition.id, definition])) as Record<string, ModuleDefinition>
