// Generated by `supabase gen types`. Do not edit by hand.
// Regenerate whenever a migration lands.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      approval_decisions: {
        Row: {
          action: string
          actor_id: string | null
          approval_id: string
          assignee_id: string | null
          comment: string | null
          created_at: string
          id: string
          organization_id: string
        }
        Insert: {
          action: string
          actor_id?: string | null
          approval_id: string
          assignee_id?: string | null
          comment?: string | null
          created_at?: string
          id?: string
          organization_id: string
        }
        Update: {
          action?: string
          actor_id?: string | null
          approval_id?: string
          assignee_id?: string | null
          comment?: string | null
          created_at?: string
          id?: string
          organization_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "approval_decisions_approval_id_organization_id_fkey"
            columns: ["approval_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "approvals"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "approval_decisions_organization_id_assignee_id_fkey"
            columns: ["organization_id", "assignee_id"]
            isOneToOne: false
            referencedRelation: "memberships"
            referencedColumns: ["organization_id", "user_id"]
          },
          {
            foreignKeyName: "approval_decisions_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      approvals: {
        Row: {
          approver_id: string | null
          created_at: string
          decided_at: string | null
          description: string | null
          due_date: string | null
          framework_id: string | null
          gate_id: string | null
          id: string
          organization_id: string
          priority: string
          project_id: string | null
          requested_by: string | null
          status: string
          submitted_at: string | null
          title: string
          updated_at: string
        }
        Insert: {
          approver_id?: string | null
          created_at?: string
          decided_at?: string | null
          description?: string | null
          due_date?: string | null
          framework_id?: string | null
          gate_id?: string | null
          id?: string
          organization_id: string
          priority?: string
          project_id?: string | null
          requested_by?: string | null
          status?: string
          submitted_at?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          approver_id?: string | null
          created_at?: string
          decided_at?: string | null
          description?: string | null
          due_date?: string | null
          framework_id?: string | null
          gate_id?: string | null
          id?: string
          organization_id?: string
          priority?: string
          project_id?: string | null
          requested_by?: string | null
          status?: string
          submitted_at?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "approvals_framework_id_organization_id_fkey"
            columns: ["framework_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "frameworks"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "approvals_gate_id_organization_id_fkey"
            columns: ["gate_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "governance_gates"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "approvals_organization_id_approver_id_fkey"
            columns: ["organization_id", "approver_id"]
            isOneToOne: false
            referencedRelation: "memberships"
            referencedColumns: ["organization_id", "user_id"]
          },
          {
            foreignKeyName: "approvals_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "approvals_project_id_organization_id_fkey"
            columns: ["project_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id", "organization_id"]
          },
        ]
      }
      audit_events: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          id: string
          new_value: Json | null
          old_value: Json | null
          organization_id: string | null
          resource: string
          resource_id: string | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          id?: string
          new_value?: Json | null
          old_value?: Json | null
          organization_id?: string | null
          resource: string
          resource_id?: string | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          id?: string
          new_value?: Json | null
          old_value?: Json | null
          organization_id?: string | null
          resource?: string
          resource_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "audit_events_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      clients: {
        Row: {
          archived_at: string | null
          billing_email: string | null
          contact_email: string | null
          contact_name: string | null
          contact_phone: string | null
          created_at: string
          health: string
          id: string
          industry: string | null
          name: string
          notes: string | null
          organization_id: string
          owner_id: string | null
          service: string | null
          status: string
          updated_at: string
          website: string | null
        }
        Insert: {
          archived_at?: string | null
          billing_email?: string | null
          contact_email?: string | null
          contact_name?: string | null
          contact_phone?: string | null
          created_at?: string
          health?: string
          id?: string
          industry?: string | null
          name: string
          notes?: string | null
          organization_id: string
          owner_id?: string | null
          service?: string | null
          status?: string
          updated_at?: string
          website?: string | null
        }
        Update: {
          archived_at?: string | null
          billing_email?: string | null
          contact_email?: string | null
          contact_name?: string | null
          contact_phone?: string | null
          created_at?: string
          health?: string
          id?: string
          industry?: string | null
          name?: string
          notes?: string | null
          organization_id?: string
          owner_id?: string | null
          service?: string | null
          status?: string
          updated_at?: string
          website?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "clients_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      delivery_item_phase_history: {
        Row: {
          changed_at: string
          changed_by: string | null
          delivery_item_id: string
          from_phase_id: string | null
          id: string
          organization_id: string
          to_phase_id: string | null
        }
        Insert: {
          changed_at?: string
          changed_by?: string | null
          delivery_item_id: string
          from_phase_id?: string | null
          id?: string
          organization_id: string
          to_phase_id?: string | null
        }
        Update: {
          changed_at?: string
          changed_by?: string | null
          delivery_item_id?: string
          from_phase_id?: string | null
          id?: string
          organization_id?: string
          to_phase_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "delivery_item_phase_history_delivery_item_id_fkey"
            columns: ["delivery_item_id"]
            isOneToOne: false
            referencedRelation: "delivery_items"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "delivery_item_phase_history_from_phase_id_fkey"
            columns: ["from_phase_id"]
            isOneToOne: false
            referencedRelation: "framework_phases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "delivery_item_phase_history_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "delivery_item_phase_history_to_phase_id_fkey"
            columns: ["to_phase_id"]
            isOneToOne: false
            referencedRelation: "framework_phases"
            referencedColumns: ["id"]
          },
        ]
      }
      delivery_items: {
        Row: {
          archived_at: string | null
          created_at: string
          current_phase_id: string | null
          description: string | null
          external_reference: string | null
          framework_id: string
          health: string
          id: string
          level: number
          name: string
          organization_id: string
          owner_id: string | null
          parent_id: string | null
          parent_level: number | null
          project_id: string
          source_system: string | null
          start_date: string | null
          status: string
          target_date: string | null
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          current_phase_id?: string | null
          description?: string | null
          external_reference?: string | null
          framework_id: string
          health?: string
          id?: string
          level: number
          name: string
          organization_id: string
          owner_id?: string | null
          parent_id?: string | null
          parent_level?: number | null
          project_id: string
          source_system?: string | null
          start_date?: string | null
          status?: string
          target_date?: string | null
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          current_phase_id?: string | null
          description?: string | null
          external_reference?: string | null
          framework_id?: string
          health?: string
          id?: string
          level?: number
          name?: string
          organization_id?: string
          owner_id?: string | null
          parent_id?: string | null
          parent_level?: number | null
          project_id?: string
          source_system?: string | null
          start_date?: string | null
          status?: string
          target_date?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "delivery_items_organization_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "delivery_items_owner_fkey"
            columns: ["organization_id", "owner_id"]
            isOneToOne: false
            referencedRelation: "memberships"
            referencedColumns: ["organization_id", "user_id"]
          },
          {
            foreignKeyName: "delivery_items_parent_fkey"
            columns: ["parent_id", "parent_level", "project_id"]
            isOneToOne: false
            referencedRelation: "delivery_items"
            referencedColumns: ["id", "level", "project_id"]
          },
          {
            foreignKeyName: "delivery_items_phase_fkey"
            columns: ["framework_id", "current_phase_id"]
            isOneToOne: false
            referencedRelation: "framework_phases"
            referencedColumns: ["framework_id", "id"]
          },
          {
            foreignKeyName: "delivery_items_project_fkey"
            columns: ["project_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "delivery_items_project_framework_fkey"
            columns: ["project_id", "framework_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id", "framework_id"]
          },
        ]
      }
      framework_phases: {
        Row: {
          archived_at: string | null
          framework_id: string
          id: string
          name: string
          organization_id: string
          position: number
        }
        Insert: {
          archived_at?: string | null
          framework_id: string
          id?: string
          name: string
          organization_id: string
          position: number
        }
        Update: {
          archived_at?: string | null
          framework_id?: string
          id?: string
          name?: string
          organization_id?: string
          position?: number
        }
        Relationships: [
          {
            foreignKeyName: "framework_phases_framework_fkey"
            columns: ["framework_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "frameworks"
            referencedColumns: ["id", "organization_id"]
          },
        ]
      }
      framework_versions: {
        Row: {
          changed_by: string | null
          created_at: string
          framework_id: string
          id: string
          organization_id: string
          snapshot: Json
          version: string | null
        }
        Insert: {
          changed_by?: string | null
          created_at?: string
          framework_id: string
          id?: string
          organization_id: string
          snapshot: Json
          version?: string | null
        }
        Update: {
          changed_by?: string | null
          created_at?: string
          framework_id?: string
          id?: string
          organization_id?: string
          snapshot?: Json
          version?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "framework_versions_framework_id_organization_id_fkey"
            columns: ["framework_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "frameworks"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "framework_versions_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      frameworks: {
        Row: {
          archived_at: string | null
          created_at: string
          id: string
          level_1_label: string | null
          level_2_label: string | null
          name: string
          organization_id: string
          type: string | null
          updated_at: string
          version: string | null
        }
        Insert: {
          archived_at?: string | null
          created_at?: string
          id?: string
          level_1_label?: string | null
          level_2_label?: string | null
          name: string
          organization_id: string
          type?: string | null
          updated_at?: string
          version?: string | null
        }
        Update: {
          archived_at?: string | null
          created_at?: string
          id?: string
          level_1_label?: string | null
          level_2_label?: string | null
          name?: string
          organization_id?: string
          type?: string | null
          updated_at?: string
          version?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "frameworks_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      governance_artefacts: {
        Row: {
          approval_id: string | null
          created_at: string
          external_url: string | null
          framework_id: string | null
          gate_id: string | null
          id: string
          name: string
          notes: string | null
          organization_id: string
          project_id: string | null
          storage_path: string | null
          updated_at: string
          uploaded_by: string | null
        }
        Insert: {
          approval_id?: string | null
          created_at?: string
          external_url?: string | null
          framework_id?: string | null
          gate_id?: string | null
          id?: string
          name: string
          notes?: string | null
          organization_id: string
          project_id?: string | null
          storage_path?: string | null
          updated_at?: string
          uploaded_by?: string | null
        }
        Update: {
          approval_id?: string | null
          created_at?: string
          external_url?: string | null
          framework_id?: string | null
          gate_id?: string | null
          id?: string
          name?: string
          notes?: string | null
          organization_id?: string
          project_id?: string | null
          storage_path?: string | null
          updated_at?: string
          uploaded_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "governance_artefacts_approval_id_organization_id_fkey"
            columns: ["approval_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "approvals"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "governance_artefacts_framework_id_organization_id_fkey"
            columns: ["framework_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "frameworks"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "governance_artefacts_gate_id_organization_id_fkey"
            columns: ["gate_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "governance_gates"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "governance_artefacts_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "governance_artefacts_project_id_organization_id_fkey"
            columns: ["project_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id", "organization_id"]
          },
        ]
      }
      governance_gates: {
        Row: {
          approval_required: boolean
          created_at: string
          description: string | null
          evidence_required: boolean
          framework_id: string
          id: string
          name: string
          organization_id: string
          phase_id: string
          position: number
          updated_at: string
        }
        Insert: {
          approval_required?: boolean
          created_at?: string
          description?: string | null
          evidence_required?: boolean
          framework_id: string
          id?: string
          name: string
          organization_id: string
          phase_id: string
          position?: number
          updated_at?: string
        }
        Update: {
          approval_required?: boolean
          created_at?: string
          description?: string | null
          evidence_required?: boolean
          framework_id?: string
          id?: string
          name?: string
          organization_id?: string
          phase_id?: string
          position?: number
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "governance_gates_framework_id_organization_id_fkey"
            columns: ["framework_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "frameworks"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "governance_gates_framework_id_phase_id_fkey"
            columns: ["framework_id", "phase_id"]
            isOneToOne: false
            referencedRelation: "framework_phases"
            referencedColumns: ["framework_id", "id"]
          },
          {
            foreignKeyName: "governance_gates_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      invitations: {
        Row: {
          accepted_at: string | null
          created_at: string
          email: string
          expires_at: string
          id: string
          invited_by: string | null
          organization_id: string
          role_id: string
          status: string
          token_hash: string
        }
        Insert: {
          accepted_at?: string | null
          created_at?: string
          email: string
          expires_at: string
          id?: string
          invited_by?: string | null
          organization_id: string
          role_id: string
          status?: string
          token_hash: string
        }
        Update: {
          accepted_at?: string | null
          created_at?: string
          email?: string
          expires_at?: string
          id?: string
          invited_by?: string | null
          organization_id?: string
          role_id?: string
          status?: string
          token_hash?: string
        }
        Relationships: [
          {
            foreignKeyName: "invitations_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      memberships: {
        Row: {
          created_at: string
          id: string
          organization_id: string
          role_id: string
          status: string
          updated_at: string
          user_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          organization_id: string
          role_id: string
          status?: string
          updated_at?: string
          user_id: string
        }
        Update: {
          created_at?: string
          id?: string
          organization_id?: string
          role_id?: string
          status?: string
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "memberships_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
        ]
      }
      organizations: {
        Row: {
          created_at: string
          email_domain: string | null
          id: string
          name: string
          slug: string
          status: string
          tier: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          email_domain?: string | null
          id?: string
          name: string
          slug: string
          status?: string
          tier?: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          email_domain?: string | null
          id?: string
          name?: string
          slug?: string
          status?: string
          tier?: string
          updated_at?: string
        }
        Relationships: []
      }
      portfolios: {
        Row: {
          archived_at: string | null
          business_unit: string | null
          code: string
          created_at: string
          description: string | null
          id: string
          name: string
          organization_id: string
          owner_id: string | null
          sponsor_id: string | null
          start_date: string | null
          status: string
          strategic_objective: string | null
          target_end_date: string | null
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          business_unit?: string | null
          code: string
          created_at?: string
          description?: string | null
          id?: string
          name: string
          organization_id: string
          owner_id?: string | null
          sponsor_id?: string | null
          start_date?: string | null
          status?: string
          strategic_objective?: string | null
          target_end_date?: string | null
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          business_unit?: string | null
          code?: string
          created_at?: string
          description?: string | null
          id?: string
          name?: string
          organization_id?: string
          owner_id?: string | null
          sponsor_id?: string | null
          start_date?: string | null
          status?: string
          strategic_objective?: string | null
          target_end_date?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "portfolios_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "portfolios_organization_id_owner_id_fkey"
            columns: ["organization_id", "owner_id"]
            isOneToOne: false
            referencedRelation: "memberships"
            referencedColumns: ["organization_id", "user_id"]
          },
          {
            foreignKeyName: "portfolios_organization_id_sponsor_id_fkey"
            columns: ["organization_id", "sponsor_id"]
            isOneToOne: false
            referencedRelation: "memberships"
            referencedColumns: ["organization_id", "user_id"]
          },
        ]
      }
      programmes: {
        Row: {
          archived_at: string | null
          code: string
          created_at: string
          description: string | null
          health: string
          id: string
          name: string
          organization_id: string
          owner_id: string | null
          portfolio_id: string
          sponsor_id: string | null
          start_date: string | null
          status: string
          target_end_date: string | null
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          code: string
          created_at?: string
          description?: string | null
          health?: string
          id?: string
          name: string
          organization_id: string
          owner_id?: string | null
          portfolio_id: string
          sponsor_id?: string | null
          start_date?: string | null
          status?: string
          target_end_date?: string | null
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          code?: string
          created_at?: string
          description?: string | null
          health?: string
          id?: string
          name?: string
          organization_id?: string
          owner_id?: string | null
          portfolio_id?: string
          sponsor_id?: string | null
          start_date?: string | null
          status?: string
          target_end_date?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "programmes_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "programmes_organization_id_owner_id_fkey"
            columns: ["organization_id", "owner_id"]
            isOneToOne: false
            referencedRelation: "memberships"
            referencedColumns: ["organization_id", "user_id"]
          },
          {
            foreignKeyName: "programmes_organization_id_sponsor_id_fkey"
            columns: ["organization_id", "sponsor_id"]
            isOneToOne: false
            referencedRelation: "memberships"
            referencedColumns: ["organization_id", "user_id"]
          },
          {
            foreignKeyName: "programmes_portfolio_id_organization_id_fkey"
            columns: ["portfolio_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "portfolios"
            referencedColumns: ["id", "organization_id"]
          },
        ]
      }
      project_decisions: {
        Row: {
          created_at: string
          decided_at: string
          decided_by: string | null
          decision: string
          id: string
          organization_id: string
          project_id: string
          rationale: string | null
          title: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          decided_at?: string
          decided_by?: string | null
          decision: string
          id?: string
          organization_id: string
          project_id: string
          rationale?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          decided_at?: string
          decided_by?: string | null
          decision?: string
          id?: string
          organization_id?: string
          project_id?: string
          rationale?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_decisions_organization_id_decided_by_fkey"
            columns: ["organization_id", "decided_by"]
            isOneToOne: false
            referencedRelation: "memberships"
            referencedColumns: ["organization_id", "user_id"]
          },
          {
            foreignKeyName: "project_decisions_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_decisions_project_id_organization_id_fkey"
            columns: ["project_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id", "organization_id"]
          },
        ]
      }
      project_dependencies: {
        Row: {
          created_at: string
          criticality: string
          dependency_owner_id: string | null
          dependent_project_id: string
          id: string
          notes: string | null
          organization_id: string
          prerequisite_framework_id: string
          prerequisite_project_id: string
          relationship_type: string
          required_by_date: string | null
          required_phase_id: string | null
          required_status: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          criticality?: string
          dependency_owner_id?: string | null
          dependent_project_id: string
          id?: string
          notes?: string | null
          organization_id: string
          prerequisite_framework_id: string
          prerequisite_project_id: string
          relationship_type?: string
          required_by_date?: string | null
          required_phase_id?: string | null
          required_status?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          criticality?: string
          dependency_owner_id?: string | null
          dependent_project_id?: string
          id?: string
          notes?: string | null
          organization_id?: string
          prerequisite_framework_id?: string
          prerequisite_project_id?: string
          relationship_type?: string
          required_by_date?: string | null
          required_phase_id?: string | null
          required_status?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_dependencies_dependent_fkey"
            columns: ["dependent_project_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "project_dependencies_organization_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_dependencies_owner_fkey"
            columns: ["organization_id", "dependency_owner_id"]
            isOneToOne: false
            referencedRelation: "memberships"
            referencedColumns: ["organization_id", "user_id"]
          },
          {
            foreignKeyName: "project_dependencies_phase_fkey"
            columns: ["prerequisite_framework_id", "required_phase_id"]
            isOneToOne: false
            referencedRelation: "framework_phases"
            referencedColumns: ["framework_id", "id"]
          },
          {
            foreignKeyName: "project_dependencies_prerequisite_fkey"
            columns: ["prerequisite_project_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "project_dependencies_prerequisite_framework_fkey"
            columns: ["prerequisite_project_id", "prerequisite_framework_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id", "framework_id"]
          },
        ]
      }
      project_risks: {
        Row: {
          created_at: string
          description: string | null
          id: string
          impact: string
          mitigation: string | null
          organization_id: string
          owner_id: string | null
          probability: string
          project_id: string
          status: string
          target_date: string | null
          title: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          impact?: string
          mitigation?: string | null
          organization_id: string
          owner_id?: string | null
          probability?: string
          project_id: string
          status?: string
          target_date?: string | null
          title: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          impact?: string
          mitigation?: string | null
          organization_id?: string
          owner_id?: string | null
          probability?: string
          project_id?: string
          status?: string
          target_date?: string | null
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "project_risks_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "project_risks_organization_id_owner_id_fkey"
            columns: ["organization_id", "owner_id"]
            isOneToOne: false
            referencedRelation: "memberships"
            referencedColumns: ["organization_id", "user_id"]
          },
          {
            foreignKeyName: "project_risks_project_id_organization_id_fkey"
            columns: ["project_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "projects"
            referencedColumns: ["id", "organization_id"]
          },
        ]
      }
      projects: {
        Row: {
          archived_at: string | null
          client_id: string | null
          created_at: string
          due_date: string | null
          framework_id: string
          health: string
          id: string
          name: string
          next_gate: string | null
          notes: string | null
          organization_id: string
          owner_id: string | null
          phase_id: string | null
          portfolio_id: string | null
          programme_id: string | null
          progress: number
          status: string
          updated_at: string
        }
        Insert: {
          archived_at?: string | null
          client_id?: string | null
          created_at?: string
          due_date?: string | null
          framework_id: string
          health?: string
          id?: string
          name: string
          next_gate?: string | null
          notes?: string | null
          organization_id: string
          owner_id?: string | null
          phase_id?: string | null
          portfolio_id?: string | null
          programme_id?: string | null
          progress?: number
          status?: string
          updated_at?: string
        }
        Update: {
          archived_at?: string | null
          client_id?: string | null
          created_at?: string
          due_date?: string | null
          framework_id?: string
          health?: string
          id?: string
          name?: string
          next_gate?: string | null
          notes?: string | null
          organization_id?: string
          owner_id?: string | null
          phase_id?: string | null
          portfolio_id?: string | null
          programme_id?: string | null
          progress?: number
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "projects_client_fkey"
            columns: ["client_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "clients"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "projects_framework_fkey"
            columns: ["framework_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "frameworks"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "projects_organization_id_fkey"
            columns: ["organization_id"]
            isOneToOne: false
            referencedRelation: "organizations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "projects_owner_fkey"
            columns: ["organization_id", "owner_id"]
            isOneToOne: false
            referencedRelation: "memberships"
            referencedColumns: ["organization_id", "user_id"]
          },
          {
            foreignKeyName: "projects_phase_fkey"
            columns: ["framework_id", "phase_id"]
            isOneToOne: false
            referencedRelation: "framework_phases"
            referencedColumns: ["framework_id", "id"]
          },
          {
            foreignKeyName: "projects_portfolio_fkey"
            columns: ["portfolio_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "portfolios"
            referencedColumns: ["id", "organization_id"]
          },
          {
            foreignKeyName: "projects_programme_fkey"
            columns: ["programme_id", "portfolio_id", "organization_id"]
            isOneToOne: false
            referencedRelation: "programmes"
            referencedColumns: ["id", "portfolio_id", "organization_id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      accept_invitation: { Args: { raw_token: string }; Returns: string }
      claim_directory_membership: { Args: never; Returns: string }
      delete_organization: { Args: { target_org: string }; Returns: undefined }
      has_role: { Args: { org: string; roles: string[] }; Returns: boolean }
      has_role_for: {
        Args: { actor: string; org: string; roles: string[] }
        Returns: boolean
      }
      invitation_preview: {
        Args: { raw_token: string }
        Returns: {
          email: string
          organization_name: string
        }[]
      }
      is_member_of: { Args: { org: string }; Returns: boolean }
      list_organization_members: {
        Args: { p_organization_id: string }
        Returns: {
          email: string
          full_name: string
          role_id: string
          status: string
          user_id: string
        }[]
      }
      list_provisioned_organizations: {
        Args: never
        Returns: {
          admin_email: string
          created_at: string
          id: string
          name: string
          slug: string
          status: string
        }[]
      }
      provision_organization: {
        Args: {
          p_actor_id: string
          p_admin_email: string
          p_expires_at: string
          p_name: string
          p_slug: string
          p_tier?: string
          p_token_hash: string
        }
        Returns: string
      }
      reissue_invitation: {
        Args: {
          p_actor_id: string
          p_email: string
          p_expires_at: string
          p_organization_id: string
          p_token_hash: string
        }
        Returns: undefined
      }
      reorder_framework_phases: {
        Args: { p_framework_id: string; p_phase_ids: string[] }
        Returns: undefined
      }
      rls_test_give_azure_identity: {
        Args: { target_email: string; target_user_id: string }
        Returns: undefined
      }
      show_limit: { Args: never; Returns: number }
      show_trgm: { Args: { "": string }; Returns: string[] }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
