import { AlertTriangle, Building2, CheckCircle2, CreditCard, Plus, Settings2, TicketCheck, Users } from 'lucide-react'
import Link from 'next/link'

import { InternalEmptyState, InternalMetric, InternalPageHeader, ProvisioningStatusBadge } from '@/features/internal-provisioning/components/internal-primitives'
import { changeSubscriptionStatusAction } from '../actions'
import type { PlatformOrganization, PlatformSubscription, SubscriptionEvent, SupportCase, SupportTicketOption, TenantConfiguration } from '../types'
import { SubscriptionForm, SupportCaseForm, TenantConfigurationForm } from './forms'

export function TenantConfigurationRegister({ records }: { records: Array<{ organization: PlatformOrganization; configuration: TenantConfiguration | null }> }) {
  const configured = records.filter((item) => item.configuration).length
  const strategic = records.filter((item) => item.organization.tier === 'strategic-enterprise').length
  return <>
    <InternalPageHeader title="Strategic Tenant Configuration" description="Control the operating model, regional defaults, governance escalation and evidence posture for enterprise tenants." />
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><InternalMetric label="Organizations" value={String(records.length)} detail="Visible to platform administration" icon={Building2} /><InternalMetric label="Strategic Enterprise" value={String(strategic)} detail="Client-configured entitlement" icon={Settings2} tone="success" /><InternalMetric label="Configured" value={String(configured)} detail="Persistent policy profiles" icon={CheckCircle2} /><InternalMetric label="Needs Setup" value={String(records.length - configured)} detail="Using system defaults" icon={AlertTriangle} tone="warning" /></div>
    <section className="mt-5 overflow-hidden border border-border bg-card"><header className="border-b border-border p-5"><h2 className="font-brand text-sm font-medium tracking-[0.08em] uppercase">Tenant configuration register</h2><p className="mt-1 text-xs text-muted-foreground">No demonstration tenants are shown; every row comes from the platform database.</p></header>{records.length ? <Table columns={['Organization', 'Tier', 'Status', 'Operating model', 'Region', 'Retention', 'Configuration']} rows={records.map(({ organization, configuration }) => [<Link key="name" href={`/internal/tenants/${organization.id}`} className="font-medium text-brand hover:underline">{organization.name}</Link>, organization.tier, <ProvisioningStatusBadge key="status" status={organization.status} />, configuration?.operating_model ?? 'System default', configuration?.data_region ?? '—', configuration ? `${configuration.retention_days} days` : '—', <Link key="configure" href={`/internal/tenants/${organization.id}`} className="text-xs font-semibold text-brand">{configuration ? 'Review' : 'Configure'}</Link>])} /> : <InternalEmptyState title="No tenant organizations" description="Provision an organization before adding its enterprise configuration." />}</section>
  </>
}

export function TenantConfigurationPage({ organization, configuration }: { organization: PlatformOrganization; configuration: TenantConfiguration | null }) {
  return <><InternalPageHeader title={organization.name} description={`Persistent strategic enterprise configuration for ${organization.slug}.`} backHref="/internal/tenants" /><div className="mb-5 grid gap-3 sm:grid-cols-3"><Summary label="Tier" value={organization.tier} /><Summary label="Tenant status" value={organization.status} /><Summary label="Configuration" value={configuration ? `Updated ${formatDate(configuration.updated_at)}` : 'Not configured'} /></div><TenantConfigurationForm organization={organization} configuration={configuration} /></>
}

export function SubscriptionRegister({ records }: { records: PlatformSubscription[] }) {
  const active = records.filter((item) => item.status === 'active').length
  const seats = records.filter((item) => item.status === 'active').reduce((total, item) => total + item.seat_limit, 0)
  const renewals = records.filter((item) => item.renews_on && new Date(item.renews_on).valueOf() < Date.now() + 90 * 86_400_000).length
  return <>
    <InternalPageHeader title="Subscriptions" description="Manage plan, lifecycle, capacity, renewal and billing metadata for every UNISON tenant." actions={<Link href="/internal/subscriptions/new" className="inline-flex h-10 items-center gap-2 bg-brand px-4 text-sm font-medium text-white"><Plus className="size-4" />New subscription</Link>} />
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><InternalMetric label="Subscriptions" value={String(records.length)} detail="Persistent commercial records" icon={CreditCard} /><InternalMetric label="Active" value={String(active)} detail="Currently serving" icon={CheckCircle2} tone="success" /><InternalMetric label="Configured seats" value={String(seats)} detail="Across active plans" icon={Users} /><InternalMetric label="Renewals due" value={String(renewals)} detail="Within 90 days" icon={AlertTriangle} tone="warning" /></div>
    <section className="mt-5 overflow-hidden border border-border bg-card"><header className="border-b border-border p-5"><h2 className="font-brand text-sm font-medium tracking-[0.08em] uppercase">Subscription register</h2></header>{records.length ? <Table columns={['Organization', 'Plan', 'Status', 'Cycle', 'Seats', 'Renewal', 'Amount', 'Actions']} rows={records.map((record) => [<Link key="name" href={`/internal/subscriptions/${record.id}/edit`} className="font-medium text-brand hover:underline">{record.organization_name}</Link>, record.plan_key, <ProvisioningStatusBadge key="status" status={record.status} />, record.billing_cycle, String(record.seat_limit), formatDate(record.renews_on), money(record.amount, record.currency), <div key="actions" className="flex gap-3"><Link href={`/internal/subscriptions/${record.id}/edit`} className="text-xs font-semibold text-brand">Edit</Link>{record.status !== 'paused' && record.status !== 'cancelled' ? <StatusButton id={record.id} status="paused" label="Pause" /> : null}{record.status === 'paused' ? <StatusButton id={record.id} status="active" label="Resume" /> : null}{record.status !== 'cancelled' ? <StatusButton id={record.id} status="cancelled" label="Cancel" danger /> : null}</div>])} /> : <InternalEmptyState title="No subscriptions" description="Create the first subscription to control tenant plan and capacity." action={<Link href="/internal/subscriptions/new" className="bg-brand px-4 py-2 text-sm font-semibold text-white">New subscription</Link>} />}</section>
  </>
}

export function SubscriptionPage({ organizations, subscription, events }: { organizations: PlatformOrganization[]; subscription?: PlatformSubscription | null; events?: SubscriptionEvent[] }) {
  return <><InternalPageHeader title={subscription ? `Subscription · ${subscription.organization_name}` : 'New Subscription'} description={subscription ? 'Update commercial lifecycle and tenant capacity.' : 'Create a persistent subscription for a provisioned organization.'} backHref="/internal/subscriptions" /><SubscriptionForm organizations={organizations} subscription={subscription} />{subscription ? <section className="mt-5 border border-border bg-card"><header className="border-b border-border p-5"><h2 className="font-brand text-sm font-medium tracking-[0.08em] uppercase">Decision history</h2><p className="mt-1 text-xs text-muted-foreground">Immutable subscription events recorded by the database.</p></header>{events?.length ? <div className="divide-y divide-border">{events.map((event) => <div key={event.id} className="flex flex-wrap justify-between gap-3 p-5"><div><p className="text-sm font-semibold">{event.action}</p><p className="mt-1 text-xs text-muted-foreground">Event #{event.id}</p></div><time className="text-xs text-muted-foreground">{formatDateTime(event.created_at)}</time></div>)}</div> : <InternalEmptyState title="No subscription events" description="Changes will appear here after the subscription is saved." />}</section> : null}</>
}

export function SupportCaseRegister({ records, unlinkedTickets }: { records: SupportCase[]; unlinkedTickets: SupportTicketOption[] }) {
  const open = records.filter((item) => !['Resolved', 'Closed'].includes(item.status)).length
  const critical = records.filter((item) => item.priority === 'Critical' && !['Resolved', 'Closed'].includes(item.status)).length
  const slaRisk = records.filter((item) => item.sla_due_at && new Date(item.sla_due_at).valueOf() < Date.now() && !['Resolved', 'Closed'].includes(item.status)).length
  return <>
    <InternalPageHeader title="Support Cases" description="Triage, assign and resolve internal platform cases across tenant operations." actions={<Link href="/internal/support/new" className="inline-flex h-10 items-center gap-2 bg-brand px-4 text-sm font-medium text-white"><Plus className="size-4" />New case</Link>} />
    <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><InternalMetric label="Cases" value={String(records.length)} detail="Persistent support history" icon={TicketCheck} /><InternalMetric label="Open" value={String(open)} detail="Requires ownership" icon={AlertTriangle} /><InternalMetric label="Untriaged requests" value={String(unlinkedTickets.length)} detail="Submitted by tenants" icon={AlertTriangle} tone="warning" /><InternalMetric label="SLA overdue" value={String(slaRisk)} detail={`${critical} critical case${critical === 1 ? '' : 's'}`} icon={AlertTriangle} tone="danger" /></div>
    {unlinkedTickets.length ? <section className="mt-5 overflow-hidden border border-warning/30 bg-card"><header className="border-b border-border p-5"><h2 className="font-brand text-sm font-medium tracking-[0.08em] uppercase">Requests awaiting triage</h2><p className="mt-1 text-xs text-muted-foreground">Open a support case to assign ownership, SLA and internal notes.</p></header><Table columns={['Request', 'Subject', 'Organization', 'Priority', 'Status', 'Action']} rows={unlinkedTickets.map((ticket) => [`SUP-${String(ticket.ticket_number).padStart(6, '0')}`, ticket.subject, ticket.organization_name, ticket.priority, ticket.status, <Link key="triage" href={`/internal/support/new?ticketId=${ticket.id}`} className="text-xs font-semibold text-brand">Triage request</Link>])} /></section> : null}
    <section className="mt-5 overflow-hidden border border-border bg-card">{records.length ? <Table columns={['Case', 'Subject', 'Organization', 'Priority', 'Status', 'Assignee', 'SLA due', 'Updated']} rows={records.map((record) => [<Link key="case" href={`/internal/support/${record.id}`} className="font-medium text-brand hover:underline">{caseReference(record.case_number)}</Link>, record.subject, record.organization_name, record.priority, <ProvisioningStatusBadge key="status" status={record.status} />, record.assignee_name ?? 'Unassigned', formatDateTime(record.sla_due_at), formatDateTime(record.updated_at)])} /> : <InternalEmptyState title="No support cases" description="Create a case or triage a tenant support request." action={<Link href="/internal/support/new" className="bg-brand px-4 py-2 text-sm font-semibold text-white">New case</Link>} />}</section>
  </>
}

export function SupportCasePage({ organizations, supportCase, linkedTicket }: { organizations: PlatformOrganization[]; supportCase?: SupportCase | null; linkedTicket?: SupportTicketOption | null }) {
  return <><InternalPageHeader title={supportCase ? `${caseReference(supportCase.case_number)} · ${supportCase.subject}` : linkedTicket ? `Triage SUP-${String(linkedTicket.ticket_number).padStart(6, '0')}` : 'New Support Case'} description={supportCase ? `${supportCase.organization_name} · created ${formatDateTime(supportCase.created_at)}` : linkedTicket ? `${linkedTicket.organization_name} · tenant-submitted request` : 'Capture an internal case for a tenant, subscription or platform operation.'} backHref="/internal/support" />{supportCase?.support_ticket_id || linkedTicket ? <p className="mb-5 border border-brand/20 bg-brand-soft/25 p-4 text-sm">Linked to tenant support request <span className="font-mono">{supportCase?.support_ticket_id ?? linkedTicket?.id}</span>.</p> : null}<SupportCaseForm organizations={organizations} supportCase={supportCase} linkedTicket={linkedTicket} /></>
}

function StatusButton({ id, status, label, danger }: { id: string; status: 'active' | 'paused' | 'cancelled'; label: string; danger?: boolean }) {
  return <form action={changeSubscriptionStatusAction}><input type="hidden" name="id" value={id} /><input type="hidden" name="status" value={status} /><button type="submit" className={`text-xs font-semibold ${danger ? 'text-destructive' : 'text-foreground'}`}>{label}</button></form>
}

function Table({ columns, rows }: { columns: string[]; rows: React.ReactNode[][] }) {
  return <div className="overflow-x-auto"><table className="w-full min-w-[880px] text-left"><thead><tr className="bg-muted/30 text-[0.65rem] font-semibold tracking-wide text-muted-foreground uppercase">{columns.map((column) => <th key={column} className="px-4 py-3">{column}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index} className="border-t border-border">{row.map((cell, cellIndex) => <td key={cellIndex} className="px-4 py-3.5 text-sm">{cell}</td>)}</tr>)}</tbody></table></div>
}

function Summary({ label, value }: { label: string; value: string }) { return <div className="border border-border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div> }
function formatDate(value?: string | null) { return value ? new Intl.DateTimeFormat('en-ZA', { dateStyle: 'medium' }).format(new Date(value)) : '—' }
function formatDateTime(value?: string | null) { return value ? new Intl.DateTimeFormat('en-ZA', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) : '—' }
function money(value: number, currency: string) { return new Intl.NumberFormat('en-ZA', { style: 'currency', currency }).format(Number(value)) }
function caseReference(value: number) { return `CASE-${String(value).padStart(6, '0')}` }
