import { Archive, BookOpen, FileText, Pencil, Plus, Send } from 'lucide-react'
import Link from 'next/link'

import { WorkspaceHeader } from '@/components/shared/workspace-header'
import { InternalEmptyState, InternalPageHeader, ProvisioningStatusBadge } from '@/features/internal-provisioning/components/internal-primitives'
import { changeKnowledgeStatusAction } from '../actions'
import type { KnowledgeArticle } from '../types'
import { KnowledgeArticleForm } from './forms'

export function KnowledgeRegister({ scope, records, canManage = true }: { scope: 'internal' | 'tenant'; records: KnowledgeArticle[]; canManage?: boolean }) {
  const base = scope === 'internal' ? '/internal/knowledge' : '/knowledge'
  const header = scope === 'internal'
    ? <InternalPageHeader title="Knowledge Management" description="Create, govern and publish operational guidance for HIMARK platform administration." actions={<Link href={`${base}/new`} className="inline-flex h-10 items-center gap-2 bg-brand px-4 text-sm font-medium text-white"><Plus className="size-4" />New article</Link>} />
    : <WorkspaceHeader category="Knowledge" title="Knowledge" description="Create, publish and retain organization guidance, policies and operating knowledge." action={canManage ? 'New Article' : undefined} actionHref={canManage ? `${base}/new` : undefined} />
  return <>{header}<div className="mb-5 grid gap-3 sm:grid-cols-3"><Metric label="Articles" value={records.length} /><Metric label="Published" value={records.filter((item) => item.status === 'published').length} /><Metric label="Drafts" value={records.filter((item) => item.status === 'draft').length} /></div><section className="overflow-hidden border border-border bg-card"><header className="border-b border-border p-5"><h2 className="font-brand text-sm font-medium tracking-[0.08em] uppercase">Article register</h2><p className="mt-1 text-xs text-muted-foreground">Version, publication state and visibility are persisted for every article.</p></header>{records.length ? <div className="divide-y divide-border">{records.map((article) => <article key={article.id} className="flex flex-wrap items-start gap-4 p-5"><span className="flex size-9 items-center justify-center border border-brand/15 bg-brand-soft text-brand"><BookOpen className="size-4" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><Link href={`${base}/${article.id}`} className="font-brand text-sm font-medium tracking-[0.035em] hover:text-brand">{article.title}</Link><ProvisioningStatusBadge status={article.status} /></div><p className="mt-1 text-xs text-muted-foreground">{article.category} · {article.visibility} · version {article.version}</p><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{article.summary || 'No summary has been provided.'}</p></div><div className="text-right"><p className="text-xs text-muted-foreground">Updated {formatDate(article.updated_at)}</p>{canManage ? <Link href={`${base}/${article.id}/edit`} className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-brand"><Pencil className="size-3" />Edit</Link> : null}</div></article>)}</div> : <InternalEmptyState title="No knowledge articles" description={canManage ? 'Create the first article; no sample guidance is inserted automatically.' : 'No published guidance is available for this organization yet.'} action={canManage ? <Link href={`${base}/new`} className="bg-brand px-4 py-2 text-sm font-semibold text-white">New article</Link> : undefined} />}</section></>
}

export function KnowledgeEditor({ scope, article }: { scope: 'internal' | 'tenant'; article?: KnowledgeArticle | null }) {
  const base = scope === 'internal' ? '/internal/knowledge' : '/knowledge'
  const title = article ? `Edit ${article.title}` : 'New Knowledge Article'
  return <>{scope === 'internal' ? <InternalPageHeader title={title} description="Save a controlled knowledge version and choose its publication state." backHref={article ? `${base}/${article.id}` : base} /> : <WorkspaceHeader category="Knowledge" parent={{ label: 'Knowledge', href: base }} title={title} description="Save a controlled knowledge version and choose its publication state." />}<KnowledgeArticleForm scope={scope} article={article} /></>
}

export function KnowledgeDetail({ scope, article, canManage = true }: { scope: 'internal' | 'tenant'; article: KnowledgeArticle; canManage?: boolean }) {
  const base = scope === 'internal' ? '/internal/knowledge' : '/knowledge'
  const statusAction = changeKnowledgeStatusAction.bind(null, scope)
  const header = scope === 'internal'
    ? <InternalPageHeader title={article.title} description={`${article.category} · version ${article.version}`} backHref={base} actions={<Link href={`${base}/${article.id}/edit`} className="inline-flex h-10 items-center gap-2 border border-border bg-card px-4 text-sm font-medium"><Pencil className="size-4" />Edit</Link>} />
    : <WorkspaceHeader category="Knowledge" parent={{ label: 'Knowledge', href: base }} title={article.title} description={`${article.category} · version ${article.version}`} actions={canManage ? <Link href={`${base}/${article.id}/edit`} className="inline-flex h-10 items-center gap-2 border border-border bg-card px-4 text-sm font-medium"><Pencil className="size-4" />Edit</Link> : undefined} />
  return <>{header}<div className={canManage ? 'grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_18rem]' : ''}><article className="border border-border bg-card p-6 lg:p-8"><div className="flex flex-wrap items-center gap-2 border-b border-border pb-5"><ProvisioningStatusBadge status={article.status} /><span className="text-xs text-muted-foreground">{article.visibility} · updated {formatDate(article.updated_at)}</span></div>{article.summary ? <p className="mt-6 text-base leading-7 text-muted-foreground">{article.summary}</p> : null}<div className="mt-7 whitespace-pre-wrap text-sm leading-7">{article.content}</div>{article.tags.length ? <div className="mt-8 flex flex-wrap gap-2 border-t border-border pt-5">{article.tags.map((tag) => <span key={tag} className="bg-muted px-2.5 py-1 text-xs">{tag}</span>)}</div> : null}</article>{canManage ? <aside className="space-y-3 border border-border bg-card p-5"><h2 className="font-brand text-xs font-medium tracking-[0.08em] uppercase">Publication controls</h2>{article.status !== 'published' ? <StatusForm action={statusAction} id={article.id} status="published" label="Publish article" icon={<Send className="size-4" />} /> : <StatusForm action={statusAction} id={article.id} status="draft" label="Return to draft" icon={<FileText className="size-4" />} />}{article.status !== 'archived' ? <StatusForm action={statusAction} id={article.id} status="archived" label="Archive article" icon={<Archive className="size-4" />} danger /> : <StatusForm action={statusAction} id={article.id} status="draft" label="Restore as draft" icon={<FileText className="size-4" />} />}</aside> : null}</div></>
}

function StatusForm({ action, id, status, label, icon, danger }: { action: (form: FormData) => void | Promise<void>; id: string; status: string; label: string; icon: React.ReactNode; danger?: boolean }) {
  return <form action={action}><input type="hidden" name="id" value={id} /><input type="hidden" name="status" value={status} /><button type="submit" className={`flex w-full items-center gap-2 border px-3 py-2.5 text-sm font-semibold ${danger ? 'border-destructive/20 text-destructive' : 'border-border'}`}>{icon}{label}</button></form>
}

function Metric({ label, value }: { label: string; value: number }) { return <div className="border border-border bg-card p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 font-brand text-xl font-medium">{value}</p></div> }
function formatDate(value: string) { return new Intl.DateTimeFormat('en-ZA', { dateStyle: 'medium' }).format(new Date(value)) }
