'use client'

import { Bell, CircleHelp, Search, X } from 'lucide-react'
import Link from 'next/link'
import { useState } from 'react'

export function InternalTopbar() {
  const [panel, setPanel] = useState<'search' | 'notifications' | 'help' | null>(null)
  return <><header className="hidden min-h-16 items-center justify-end gap-3 border-b border-border bg-background px-6 lg:flex"><button type="button" onClick={() => setPanel('search')} className="relative mr-auto flex h-10 w-full max-w-md items-center rounded-xl border border-border bg-card pr-3 pl-10 text-left text-sm text-muted-foreground"><Search className="absolute left-3 size-4" />Search organisations, tenants, users...<kbd className="ml-auto rounded-md bg-muted px-2 py-1 text-[0.65rem]">⌘ K</kbd></button><div className="flex h-11 min-w-64 items-center gap-3 rounded-xl border border-border bg-card px-3"><span className="flex size-8 items-center justify-center rounded-full bg-sidebar text-xs font-bold text-white">HI</span><span><span className="block text-[0.62rem] font-semibold tracking-wide text-muted-foreground uppercase">HIMARK Internal</span><span className="block text-xs font-semibold text-success">Production</span></span></div><IconButton label="Notifications" onClick={() => setPanel('notifications')}><Bell className="size-4.5" /></IconButton><IconButton label="Help" onClick={() => setPanel('help')}><CircleHelp className="size-4.5" /></IconButton></header>{panel ? <InternalPanel kind={panel} onClose={() => setPanel(null)} /> : null}</>
}

function IconButton({ label, onClick, children }: { label: string; onClick: () => void; children: React.ReactNode }) { return <button type="button" onClick={onClick} aria-label={label} className="flex size-11 items-center justify-center rounded-xl border border-border bg-card text-muted-foreground hover:text-foreground">{children}</button> }

function InternalPanel({ kind, onClose }: { kind: 'search' | 'notifications' | 'help'; onClose: () => void }) {
  const copy = kind === 'search' ? { title: 'Internal Search', description: 'Find organisations, provisioning records, tenants and users.' } : kind === 'notifications' ? { title: 'Internal Notifications', description: 'Provisioning, subscription and tenant operations updates.' } : { title: 'HIMARK Internal Help', description: 'Guidance for provisioning and operating UNISON tenants.' }
  return <div className="fixed inset-0 z-[90]" onMouseDown={onClose}><div className="absolute inset-0 bg-foreground/20" /><aside role="dialog" aria-modal="true" aria-label={copy.title} onMouseDown={(event) => event.stopPropagation()} className="absolute top-0 right-0 h-full w-full max-w-md border-l border-border bg-card p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-xs font-semibold tracking-wide text-brand uppercase">HIMARK Internal</p><h2 className="mt-1 text-xl font-bold">{copy.title}</h2><p className="mt-1 text-sm text-muted-foreground">{copy.description}</p></div><button type="button" onClick={onClose} aria-label="Close panel" className="rounded-lg p-2 hover:bg-muted"><X className="size-4" /></button></div>{kind === 'search' ? <><label className="relative mt-6 block"><Search className="absolute top-1/2 left-3 size-4 -translate-y-1/2 text-muted-foreground" /><input autoFocus placeholder="Search organisations, tenants, users..." className="h-11 w-full rounded-lg border border-border bg-background pr-3 pl-10 text-sm" /></label><div className="mt-4 rounded-xl border border-border p-5 text-center text-sm text-muted-foreground">Start typing to search the internal workspace.</div></> : <div className="mt-6 space-y-3">{(kind === 'notifications' ? ['Growthpoint setup is ready for review', 'Two renewals require attention', 'Tenant health review completed'] : ['Provisioning workflow guide', 'Tier entitlement reference', 'Tenant operations handbook']).map((item) => <Link href={kind === 'notifications' ? '/internal/provisioning' : '/internal/knowledge'} onClick={onClose} key={item} className="block w-full rounded-xl border border-border p-4 text-left text-sm font-semibold hover:bg-muted">{item}<span className="mt-1 block text-xs font-normal text-muted-foreground">Open internal guidance</span></Link>)}</div>}</aside></div>
}
