'use client'

import { ArrowLeft, ArrowRight, Check, CheckCircle2, GripVertical, Plus, Trash2 } from 'lucide-react'
import Link from 'next/link'
import { useState } from 'react'

import { WorkspaceHeader } from '@/components/shared/workspace-header'
import { deliveryPhases } from '../data'

const steps = ['Framework Basics','Phases & Gates','Workstreams','Artefacts & Roles','Controls & Metrics'] as const

export function FrameworkForm({ mode = 'create', frameworkId }: { mode?: 'create' | 'edit'; frameworkId?: string }) {
  const [step, setStep] = useState(0)
  const [saved, setSaved] = useState(false)
  const [phases, setPhases] = useState<Array<{ name: string; gate: string }>>(() => deliveryPhases.map((phase, index) => ({ name: phase.name, gate: index === 0 ? 'Initiation Approval' : index === 7 ? 'Benefits Review' : `${phase.name} Exit` })))
  const title = mode === 'create' ? 'New Framework' : 'Edit Framework'
  if (saved) return <><WorkspaceHeader category="Delivery" parent={{ label: 'Frameworks', href: '/delivery/frameworks' }} title={title} /><div className="mx-auto max-w-xl rounded-xl border border-success/25 bg-card p-10 text-center"><CheckCircle2 className="mx-auto size-10 text-success" /><h2 className="mt-4 text-xl font-bold">Framework saved</h2><p className="mt-2 text-sm text-muted-foreground">The framework configuration is ready for delivery teams.</p><Link href={frameworkId ? `/delivery/frameworks/${frameworkId}` : '/delivery/frameworks/business-technology-change'} className="mt-6 inline-flex rounded-lg bg-brand px-4 py-2.5 text-sm font-semibold text-white">Open framework</Link></div></>
  return <><WorkspaceHeader category="Delivery" parent={{ label: 'Frameworks', href: '/delivery/frameworks' }} title={title} description="Build and configure a delivery framework for your organisation." /><div className="mx-auto max-w-6xl"><div className="mb-6 grid grid-cols-5 rounded-xl border border-border bg-card p-2">{steps.map((label,index) => <button key={label} type="button" onClick={() => index < step && setStep(index)} className={`flex items-center gap-2 rounded-lg px-2 py-2 text-left text-[0.6875rem] font-semibold ${index === step ? 'bg-brand-soft text-brand' : index < step ? 'text-success' : 'text-muted-foreground'}`}><span className={`flex size-6 shrink-0 items-center justify-center rounded-full ${index < step ? 'bg-success text-white' : index === step ? 'bg-brand text-white' : 'bg-muted'}`}>{index < step ? <Check className="size-3.5" /> : index + 1}</span><span className="hidden lg:block">{label}</span></button>)}</div><form onSubmit={(event) => { event.preventDefault(); step < steps.length - 1 ? setStep((value) => value + 1) : setSaved(true) }}><section className="rounded-xl border border-border bg-card p-6">{step === 0 ? <Basics /> : null}{step === 1 ? <Phases phases={phases} setPhases={setPhases} /> : null}{step === 2 ? <Workstreams /> : null}{step === 3 ? <Artefacts /> : null}{step === 4 ? <Controls /> : null}</section><footer className="mt-4 flex items-center justify-between rounded-xl border border-border bg-card p-4"><Link href="/delivery/frameworks" className="text-sm text-muted-foreground">Cancel</Link><div className="flex gap-2">{step > 0 ? <button type="button" onClick={() => setStep((value) => value - 1)} className="inline-flex h-10 items-center gap-2 rounded-lg border border-border px-4 text-sm font-semibold"><ArrowLeft className="size-4" />Back</button> : null}<button type="submit" className="inline-flex h-10 items-center gap-2 rounded-lg bg-brand px-4 text-sm font-semibold text-white">{step === steps.length - 1 ? 'Save Framework' : 'Continue'}{step < steps.length - 1 ? <ArrowRight className="size-4" /> : null}</button></div></footer></form></div></>
}

function Basics() { return <><Heading title="Framework details" description="Define the reusable delivery method and its accountable owner." /><div className="grid gap-5 md:grid-cols-2"><Field label="Framework name" placeholder="Business / Technology Change" /><Field label="Framework code" placeholder="BTC-01" /><Field label="Framework type" options={['Enterprise','Technology','Operations','Compliance','Commercial']} /><Field label="Audience" placeholder="Enterprise delivery teams" /><Field label="Description" placeholder="Purpose, scope and intended application" area className="md:col-span-2" /><Field label="Version" placeholder="v1.0" /><Field label="Owner" options={['Delivery Office','Transformation Office','Digital Delivery','Risk & Compliance']} /><Field label="Status" options={['Draft','Active','Under Review','Archived']} /><Field label="Categories" placeholder="Transformation, Technology" /><Field label="Tags" placeholder="Governance, Enterprise, Change" /></div></> }
function Phases({ phases, setPhases }: { phases: Array<{name:string;gate:string}>; setPhases: (phases: Array<{name:string;gate:string}>) => void }) { return <><Heading title="Delivery phases & gates" description="Configure the governed lifecycle generated for each project." /><div className="space-y-3">{phases.map((phase,index) => <div key={`${phase.name}-${index}`} className="grid items-center gap-3 rounded-xl border border-border p-3 md:grid-cols-[28px_52px_1fr_1fr_1.5fr_120px]"><GripVertical className="size-4 text-muted-foreground" /><span className="flex size-8 items-center justify-center rounded-lg bg-muted text-xs font-bold">{index+1}</span><input defaultValue={phase.name} aria-label={`Phase ${index+1}`} className="h-9 rounded-lg border border-border bg-background px-3 text-sm" /><input defaultValue={phase.gate} aria-label={`Gate ${index+1}`} className="h-9 rounded-lg border border-border bg-background px-3 text-sm" /><input placeholder="Phase description and exit criteria" aria-label={`Description ${index+1}`} className="h-9 rounded-lg border border-border bg-background px-3 text-sm" /><div className="flex justify-end gap-2"><button type="button" className="rounded-lg border border-border px-2 py-1.5 text-xs">Edit</button><button type="button" onClick={() => setPhases(phases.filter((_,itemIndex) => itemIndex !== index))} aria-label={`Delete ${phase.name}`} className="rounded-lg border border-border p-1.5 text-danger"><Trash2 className="size-4" /></button></div></div>)}</div><button type="button" onClick={() => setPhases([...phases,{name:'New Phase',gate:'Phase Approval'}])} className="mt-4 inline-flex items-center gap-2 rounded-lg border border-border px-3 py-2 text-sm font-semibold"><Plus className="size-4" />Add Phase</button></> }
function Workstreams() { return <><Heading title="Default workstreams" description="Define repeatable work areas and accountable roles." /><div className="grid gap-3 md:grid-cols-2">{['Programme Governance','Business Analysis','Solution Delivery','Testing & Quality','Change & Readiness','Vendor Management'].map((item,index) => <label key={item} className="rounded-xl border border-border p-4 text-sm font-semibold"><input type="checkbox" defaultChecked className="mr-3" />{item}<span className="mt-1 block pl-6 text-xs font-normal text-muted-foreground">Default owner: {index % 2 ? 'Project Lead' : 'Workstream Lead'}</span></label>)}</div></> }
function Artefacts() { return <><Heading title="Artefacts & roles" description="Set evidence requirements and accountable delivery roles." /><div className="grid gap-5 md:grid-cols-2"><div><h3 className="text-sm font-semibold">Required artefacts</h3><div className="mt-3 space-y-2">{['Business Case','Project Charter','Requirements Baseline','Solution Design','Test Evidence','Readiness Assessment','Benefits Plan'].map((item) => <label key={item} className="flex items-center justify-between rounded-lg border border-border p-3 text-sm"><span>{item}</span><input type="checkbox" defaultChecked /></label>)}</div></div><div><h3 className="text-sm font-semibold">Framework roles</h3><div className="mt-3 space-y-2">{['Project Sponsor','Project Owner','Delivery Lead','Business Owner','Gate Approver','Risk Owner','Benefits Owner'].map((item) => <div key={item} className="rounded-lg border border-border p-3 text-sm font-medium">{item}</div>)}</div></div></div></> }
function Controls() { return <><Heading title="Framework settings" description="Configure default controls, visibility and health calculation." /><div className="grid gap-5 md:grid-cols-2"><Field label="Default project duration unit" options={['Weeks','Months','Working days']} /><Field label="Default health calculation" options={['Weighted controls','Gate readiness','Milestone variance']} /><Field label="Default visibility" options={['Organization','Project team','Selected groups']} /><Field label="Evidence required at gates" options={['Required','Optional','Set per gate']} /></div><div className="mt-6 grid gap-3 md:grid-cols-2">{['Gate locking','Mandatory Business Case','Benefits tracking','Vendor dependency controls','Requirement traceability','Decision register required'].map((label) => <label key={label} className="flex items-center justify-between rounded-xl border border-border p-4 text-sm font-medium"><span>{label}</span><input type="checkbox" defaultChecked /></label>)}</div><div className="mt-6 rounded-xl bg-muted/50 p-5"><h3 className="text-sm font-semibold">Configuration summary</h3><p className="mt-2 text-xs text-muted-foreground">8 phases · 7 gates · 6 workstreams · 7 required artefacts · 7 accountable roles</p></div></> }
function Heading({ title, description }: { title:string; description:string }) { return <div className="mb-6"><h2 className="text-lg font-semibold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p></div> }
function Field({ label, placeholder, options, area, className }: { label:string; placeholder?:string; options?:string[]; area?:boolean; className?:string }) { return <label className={`text-sm font-medium ${className ?? ''}`}>{label}{area ? <textarea rows={4} placeholder={placeholder} className="mt-1.5 w-full rounded-lg border border-border bg-background p-3 text-sm outline-none focus:border-brand" /> : options ? <select className="mt-1.5 h-11 w-full rounded-lg border border-border bg-background px-3 text-sm">{options.map((option) => <option key={option}>{option}</option>)}</select> : <input placeholder={placeholder} className="mt-1.5 h-11 w-full rounded-lg border border-border bg-background px-3 text-sm outline-none focus:border-brand" />}</label> }
