'use client'

import { ArrowLeft, ArrowRight, Check, CheckCircle2, FileText, Users } from 'lucide-react'
import Link from 'next/link'
import { useState } from 'react'

import { WorkspaceHeader } from '@/components/shared/workspace-header'

const steps=['Client','Onboarding Details','Template & Structure','Team & Stakeholders','Review & Start']

export function OnboardingForm(){const [step,setStep]=useState(0);const [clientType,setClientType]=useState<'existing'|'new'>('existing');const [done,setDone]=useState(false);if(done)return <><WorkspaceHeader category="Operations" parent={{label:'Onboarding',href:'/operations/onboarding'}} title="Onboarding started"/><div className="mx-auto max-w-xl rounded-xl border border-success/25 bg-card p-10 text-center"><CheckCircle2 className="mx-auto size-10 text-success"/><h2 className="mt-4 text-xl font-bold">Onboarding workspace ready</h2><p className="mt-2 text-sm text-muted-foreground">Stages, required tasks, documents and approvals have been prepared.</p><Link href="/operations/onboarding/lumen-financial" className="mt-6 inline-flex rounded-lg bg-brand px-4 py-2 text-sm font-semibold text-white">Open onboarding</Link></div></>;return <><WorkspaceHeader category="Operations" parent={{label:'Onboarding',href:'/operations/onboarding'}} title="Start Onboarding" description="Create a governed path from client readiness to operational handover."/><div className="mx-auto max-w-6xl"><ol className="mb-6 grid grid-cols-5 rounded-xl border border-border bg-card p-2">{steps.map((label,index)=><li key={label}><button type="button" onClick={()=>index<step&&setStep(index)} className={`flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-[0.68rem] font-semibold ${index===step?'bg-brand-soft text-brand':index<step?'text-success':'text-muted-foreground'}`}><span className={`flex size-6 shrink-0 items-center justify-center rounded-full ${index<step?'bg-success text-white':index===step?'bg-brand text-white':'bg-muted'}`}>{index<step?<Check className="size-3.5"/>:index+1}</span><span className="hidden lg:block">{label}</span></button></li>)}</ol><section className="rounded-xl border border-border bg-card p-6">{step===0?<ClientStep type={clientType} setType={setClientType}/>:step===1?<DetailsStep/>:step===2?<TemplateStep/>:step===3?<TeamStep/>:<ReviewStep clientType={clientType}/>}</section><footer className="mt-4 flex items-center justify-between rounded-xl border border-border bg-card p-4"><Link href="/operations/onboarding" className="text-sm text-muted-foreground">Cancel</Link><div className="flex gap-2">{step>0?<button type="button" onClick={()=>setStep((value)=>value-1)} className="inline-flex items-center gap-2 rounded-lg border border-border px-4 py-2 text-sm font-semibold"><ArrowLeft className="size-4"/>Back</button>:null}<button type="button" onClick={()=>step===steps.length-1?setDone(true):setStep((value)=>value+1)} className="inline-flex items-center gap-2 rounded-lg bg-brand px-4 py-2 text-sm font-semibold text-white">{step===steps.length-1?'Start Onboarding':'Continue'}{step<steps.length-1?<ArrowRight className="size-4"/>:null}</button></div></footer></div></>}

function ClientStep({type,setType}:{type:'existing'|'new';setType:(value:'existing'|'new')=>void}){return <><Heading title="Select the client" description="Start from an existing client or capture the minimum information for a new one."/><div className="grid gap-3 sm:grid-cols-2">{[['existing','Existing Client','Select a client already managed in UNISON'],['new','New Client','Capture basic client information before onboarding']].map(([value,title,description])=><button type="button" key={value} onClick={()=>setType(value as 'existing'|'new')} className={`rounded-xl border p-5 text-left ${type===value?'border-brand bg-brand-soft':'border-border'}`}><span className="text-sm font-semibold">{title}</span><span className="mt-1 block text-xs text-muted-foreground">{description}</span></button>)}</div>{type==='existing'?<div className="mt-6"><Field label="Client" options={['Lumen Financial Services','Meridian Health Group','Northstar Retail','Aurelia Logistics']}/></div>:<div className="mt-6 grid gap-5 sm:grid-cols-2"><Field label="Company Name"/><Field label="Industry"/><Field label="Primary Contact"/><Field label="Contact Email" type="email"/></div>}</>}
function DetailsStep(){return <><Heading title="Onboarding details" description="Set ownership, working dates, type and priority."/><div className="grid gap-5 sm:grid-cols-2"><Field label="Onboarding Owner" options={['Amara Dlamini','Neo Morake','Lethabo Nkosi']}/><Field label="Onboarding Type" options={['Standard Client','Growth Partner','Enterprise Client','Custom']}/><Field label="Start Date" type="date"/><Field label="Target Go-Live" type="date"/><Field label="Priority" options={['Normal','High','Critical']}/><label className="sm:col-span-2 text-sm font-medium">Notes<textarea rows={4} className="mt-1.5 w-full rounded-lg border border-border bg-background p-3 text-sm"/></label></div></>}
function TemplateStep(){return <><Heading title="Template & structure" description="Choose the stages, required tasks, documents and approvals generated for this journey."/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{['Standard Client','Growth Partner','Enterprise Client','Custom'].map((item,index)=><label key={item} className="rounded-xl border border-border p-4 has-[:checked]:border-brand has-[:checked]:bg-brand-soft"><input type="radio" name="template" defaultChecked={index===0} className="sr-only"/><span className="text-sm font-semibold">{item}</span><span className="mt-1 block text-xs text-muted-foreground">6 stages · {12+index*3} tasks · {6+index} documents</span></label>)}</div><div className="mt-6 grid gap-4 md:grid-cols-3">{[[CheckCircle2,'Required tasks','Company verification, access, configuration'],[FileText,'Required documents','Company, compliance and agreement evidence'],[Check,'Required approvals','Internal review and go-live decision']].map(([Icon,title,description])=><article key={String(title)} className="rounded-xl border border-border p-4"><Icon className="size-5 text-brand"/><h3 className="mt-4 text-sm font-semibold">{String(title)}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{String(description)}</p><button type="button" className="mt-4 text-xs font-semibold text-brand">Configure</button></article>)}</div></>}
function TeamStep(){return <><Heading title="Team & stakeholders" description="Assign internal accountability and capture client decision makers."/><div className="grid gap-4 md:grid-cols-2"><section className="rounded-xl border border-border p-5"><Users className="size-5 text-brand"/><h3 className="mt-4 font-semibold">Internal team</h3><div className="mt-4 space-y-3"><Field label="Onboarding Owner" options={['Amara Dlamini','Neo Morake']}/><Field label="Project / Service Lead" options={['Lethabo Nkosi','Thabo Mokoena']}/><Field label="Executive Approver" options={['Neo Morake','Zanele Khumalo']}/></div></section><section className="rounded-xl border border-border p-5"><Users className="size-5 text-brand"/><h3 className="mt-4 font-semibold">Client stakeholders</h3><div className="mt-4 space-y-3"><Field label="Decision Maker"/><Field label="Primary Contact"/><Field label="Billing Contact"/></div><button type="button" className="mt-4 rounded-lg border border-border px-3 py-2 text-xs font-semibold">Add Stakeholder</button></section></div></>}
function ReviewStep({clientType}:{clientType:string}){return <><Heading title="Review & start" description="Confirm the onboarding plan before creating the workspace."/><div className="grid gap-4 sm:grid-cols-2">{[['Client',clientType==='existing'?'Lumen Financial Services':'New Client'],['Owner','Amara Dlamini'],['Template','Standard Client'],['Target Go-Live','18 Sep 2026'],['Stages','6 governed stages'],['Required Controls','12 tasks · 6 documents · 2 approvals']].map(([label,value])=><div key={label} className="rounded-xl border border-border p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold">{value}</p></div>)}</div><div className="mt-5 rounded-xl border border-info/20 bg-info-soft/40 p-4 text-sm"><strong>Ready to start.</strong><p className="mt-1 text-muted-foreground">The journey begins in Welcome and moves through controlled stage transitions to handover.</p></div></>}
function Heading({title,description}:{title:string;description:string}){return <div className="mb-6"><h2 className="text-xl font-bold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p></div>}
function Field({label,type='text',options}:{label:string;type?:string;options?:string[]}){return <label className="block text-sm font-medium">{label}{options?<select className="mt-1.5 h-11 w-full rounded-lg border border-border bg-background px-3 text-sm">{options.map((option)=><option key={option}>{option}</option>)}</select>:<input type={type} className="mt-1.5 h-11 w-full rounded-lg border border-border bg-background px-3 text-sm"/>}</label>}
