'use client'

import { Archive, ArrowLeft, BriefcaseBusiness, CalendarDays, Pencil, Settings2, ShieldCheck, Users } from 'lucide-react'
import Link from 'next/link'
import { useState } from 'react'

import { ConfirmationDialog } from '@/components/shared/confirmation-dialog'
import { WorkspaceHeader } from '@/components/shared/workspace-header'
import { RecordCollectionWorkspace, type CollectionConfig, type CollectionRecord } from '@/features/product-ui/components/record-collection-workspace'
import { deliveryProjects } from '../data'
import { portfolioBenefits, portfolioMembers, portfolioRisks, portfolios, programmes } from '../portfolio-data'
import { HealthBadge, MetricCard, RiskList, SectionCard } from './delivery-primitives'

const tabs = ['Overview','Programmes','Projects','Objectives','Members','Benefits','Risks','Dependencies','Governance','Activity','Settings'] as const

const commonFields = (singular: string) => [
  { id:'name',label:`${singular} Name`,required:true },
  { id:'context',label:'Description',type:'textarea' as const,required:true },
  { id:'owner',label:'Owner',type:'select' as const,options:['Neo Morake','Amara Dlamini','Thabo Mokoena','Naledi Maseko'] },
  { id:'status',label:'Status',type:'select' as const,options:['Planning','In Delivery','On Track','At Risk','Complete'] },
]

export function PortfolioDetailScreen({ portfolioId }: { portfolioId: string }) {
  const portfolio = portfolios.find((item) => item.id === portfolioId) ?? portfolios[0]
  const [tab,setTab] = useState<(typeof tabs)[number]>('Overview')
  const [archiveOpen,setArchiveOpen] = useState(false)
  const [archived,setArchived] = useState(false)

  return <><WorkspaceHeader category="Delivery" parent={{label:'Portfolio',href:'/delivery/portfolio'}} title={portfolio.name} description={`${portfolio.code} · ${portfolio.businessUnit}`} /><div className="-mt-2 mb-5 flex flex-wrap items-center justify-between gap-3"><Link href="/delivery/portfolio" className="inline-flex items-center gap-2 text-sm font-medium text-muted-foreground"><ArrowLeft className="size-4" />Back to Portfolio</Link><div className="flex items-center gap-2"><HealthBadge>{archived ? 'Archived' : String(portfolio.status)}</HealthBadge>{!archived ? <><Link href={`/delivery/portfolio/${portfolio.id}/edit`} className="inline-flex h-9 items-center gap-2 rounded-lg border border-border bg-card px-3 text-xs font-semibold"><Pencil className="size-3.5" />Edit portfolio</Link><button type="button" onClick={()=>setArchiveOpen(true)} className="inline-flex h-9 items-center gap-2 rounded-lg border border-border bg-card px-3 text-xs font-semibold text-destructive"><Archive className="size-3.5" />Archive</button></> : <button type="button" onClick={()=>setArchived(false)} className="h-9 rounded-lg border border-brand/30 bg-brand-soft px-3 text-xs font-semibold text-brand">Restore portfolio</button>}</div></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 2xl:grid-cols-8"><MetricCard label="Health" value={String(portfolio.health)} detail="Weighted delivery health" /><MetricCard label="Programmes" value="3" detail="2 in delivery" /><MetricCard label="Projects" value={String(portfolio.projects)} detail="4 need attention" /><MetricCard label="Members" value="12" detail="Across 4 teams" /><MetricCard label="Benefits" value={String(portfolio.benefits)} detail="Forecast annual value" /><MetricCard label="Risks" value="8" detail="2 escalated" /><MetricCard label="Dependencies" value="16" detail="5 external" /><MetricCard label="Governance" value="89%" detail="Controls complete" /></div><nav className="mt-5 flex gap-1 overflow-x-auto border-b border-border" aria-label="Portfolio workspace tabs">{tabs.map((item)=><button type="button" key={item} onClick={()=>setTab(item)} className={`whitespace-nowrap border-b-2 px-3 py-3 text-sm font-medium ${tab===item?'border-brand text-brand':'border-transparent text-muted-foreground'}`}>{item}</button>)}</nav><div className="mt-5">{tab==='Overview'?<PortfolioOverview portfolio={portfolio}/>:tab==='Settings'?<PortfolioSettings onArchive={()=>setArchiveOpen(true)}/>:<PortfolioTab tab={tab}/>}</div><ConfirmationDialog open={archiveOpen} title="Archive portfolio?" description={`${portfolio.name} will be removed from active portfolio views. Programmes and projects remain available and the portfolio can be restored.`} confirmLabel="Archive portfolio" onCancel={()=>setArchiveOpen(false)} onConfirm={()=>{setArchived(true);setArchiveOpen(false)}} /></>
}

function PortfolioOverview({portfolio}:{portfolio:CollectionRecord}) { return <div className="grid gap-5 xl:grid-cols-3"><SectionCard title="Portfolio summary" description="Purpose, accountability and strategic alignment." className="xl:col-span-2"><div className="grid gap-4 p-5 sm:grid-cols-2"><Detail label="Owner" value={portfolio.owner}/><Detail label="Sponsor" value={String(portfolio.sponsor)}/><Detail label="Business unit" value={String(portfolio.businessUnit)}/><Detail label="Framework" value={String(portfolio.framework)}/><div className="sm:col-span-2"><Detail label="Description" value={portfolio.context}/></div></div></SectionCard><SectionCard title="Portfolio leadership"><div className="space-y-4 p-5"><Owner icon={BriefcaseBusiness} label="Portfolio owner" value={portfolio.owner}/><Owner icon={ShieldCheck} label="Executive sponsor" value={String(portfolio.sponsor)}/><Owner icon={Users} label="Portfolio office" value="Transformation Office"/></div></SectionCard><SectionCard title="Active programmes" description="Governed programmes in this portfolio." className="xl:col-span-2"><div className="divide-y divide-border">{programmes.map((programme)=><Link key={programme.id} href={`/delivery/portfolio/${portfolio.id}/programmes/${programme.id}`} className="flex items-center gap-3 px-5 py-4 hover:bg-muted/30"><span className="flex size-9 items-center justify-center rounded-lg bg-brand-soft text-brand"><BriefcaseBusiness className="size-4"/></span><span className="min-w-0 flex-1"><span className="block truncate text-sm font-semibold">{programme.name}</span><span className="text-xs text-muted-foreground">{programme.projects} projects · {programme.owner}</span></span><HealthBadge>{programme.status}</HealthBadge></Link>)}</div></SectionCard><SectionCard title="Upcoming governance"><div className="divide-y divide-border">{['Claims steering committee · 28 Aug','Benefits baseline review · 04 Sep','Portfolio risk review · 08 Sep'].map((item)=><div key={item} className="flex items-center gap-3 px-5 py-4"><CalendarDays className="size-4 text-brand"/><span className="text-xs font-medium">{item}</span></div>)}</div></SectionCard><SectionCard title="Portfolio risks" description="Items requiring leadership attention." className="xl:col-span-2"><RiskList items={[{title:'Vendor capacity constrains two releases',meta:'Escalated to executive sponsor',severity:'danger'},{title:'Change saturation across operations',meta:'Mitigation plan due 28 Aug',severity:'warning'}]}/></SectionCard><SectionCard title="Benefits progress"><div className="p-5"><p className="text-3xl font-bold">68%</p><p className="mt-1 text-sm text-muted-foreground">R12.5M of R18.4M forecast value on track</p><div className="mt-5 h-2 rounded-full bg-muted"><div className="h-full w-[68%] rounded-full bg-brand"/></div></div></SectionCard></div> }

function PortfolioTab({tab}:{tab:Exclude<(typeof tabs)[number],'Overview'|'Settings'>}) {
  const configs:Record<string,CollectionConfig>={
    Programmes:{title:'Programmes',singular:'Programme',description:'Governed programmes within this portfolio.',primaryAction:'New Programme',records:programmes,fields:[...commonFields('Programme'),{id:'sponsor',label:'Sponsor'},{id:'start',label:'Start Date',type:'date'},{id:'end',label:'End Date',type:'date'}],filters:['Owner','Sponsor','Health'],columns:[{id:'name',label:'Programme'},{id:'code',label:'Code'},{id:'owner',label:'Owner'},{id:'projects',label:'Projects'},{id:'health',label:'Health'},{id:'status',label:'Status'},{id:'updated',label:'Updated'}],contextualActions:['Assign Project','Move']},
    Projects:{title:'Portfolio Projects',singular:'Project',description:'Projects assigned directly or through programmes.',primaryAction:'Assign Project',records:deliveryProjects.map((project)=>({id:project.id,name:project.name,context:project.framework,owner:project.owner,status:project.health,phase:project.phase,programme:project.id.includes('claims')?'Claims Modernisation':'Digital Onboarding',updated:project.dueDate})),filters:['Programme','Framework','Owner'],columns:[{id:'name',label:'Project'},{id:'programme',label:'Programme'},{id:'phase',label:'Phase'},{id:'owner',label:'Owner'},{id:'status',label:'Health'},{id:'updated',label:'Due'}],contextualActions:['Move to Programme','Remove from Portfolio']},
    Objectives:{title:'Strategic Objectives',singular:'Objective',description:'Outcomes that connect delivery work to strategy.',records:[{id:'obj-01',name:'Improve customer claim experience',context:'Reduce effort and time across the end-to-end claim journey',owner:'Neo Morake',status:'On Track',updated:'Yesterday'},{id:'obj-02',name:'Increase operational resilience',context:'Reduce manual control failures across critical processes',owner:'Thabo Mokoena',status:'Watch',updated:'3 days ago'}],fields:commonFields('Objective')},
    Members:{title:'Portfolio Members',singular:'Member',description:'Portfolio ownership, roles and access.',primaryAction:'Add Member',records:portfolioMembers,fields:[{id:'name',label:'Member',required:true},{id:'context',label:'Role',required:true},{id:'status',label:'Membership Type',type:'select',options:['Owner','Sponsor','Member']},{id:'access',label:'Access',type:'select',options:['Full access','Approve & review','Contribute','Read only']}],columns:[{id:'name',label:'Member'},{id:'context',label:'Role'},{id:'status',label:'Type'},{id:'access',label:'Access'},{id:'updated',label:'Updated'}]},
    Benefits:{title:'Portfolio Benefits',singular:'Benefit',description:'Baseline, target, forecast and realised value.',primaryAction:'Add Benefit',records:portfolioBenefits,fields:[...commonFields('Benefit'),{id:'baseline',label:'Baseline'},{id:'target',label:'Target'},{id:'forecast',label:'Forecast'}],columns:[{id:'name',label:'Benefit'},{id:'baseline',label:'Baseline'},{id:'target',label:'Target'},{id:'forecast',label:'Forecast'},{id:'owner',label:'Owner'},{id:'status',label:'Status'}],contextualActions:['Update Progress']},
    Risks:{title:'Portfolio Risks',singular:'Risk',description:'Portfolio-level threats, mitigations and escalation.',primaryAction:'Add Risk',records:portfolioRisks,fields:[...commonFields('Risk'),{id:'probability',label:'Probability',type:'select',options:['Low','Medium','High']},{id:'impact',label:'Impact',type:'select',options:['Low','Medium','High']},{id:'mitigation',label:'Mitigation',type:'textarea'}],columns:[{id:'name',label:'Risk'},{id:'probability',label:'Probability'},{id:'impact',label:'Impact'},{id:'rating',label:'Rating'},{id:'owner',label:'Owner'},{id:'status',label:'Status'}],contextualActions:['Mitigate','Escalate','Close']},
    Dependencies:{title:'Portfolio Dependencies',singular:'Dependency',description:'Cross-programme and external delivery dependencies.',primaryAction:'Add Dependency',records:[{id:'dep-01',name:'TIAL integration release',context:'Required before claims UAT exit',owner:'Lethabo Nkosi',status:'At Risk',related:'Claims Modernisation',updated:'Today'},{id:'dep-02',name:'Operations readiness window',context:'Shared readiness capacity across two programmes',owner:'Amara Dlamini',status:'Watch',related:'Digital Onboarding',updated:'Yesterday'}],fields:commonFields('Dependency'),contextualActions:['Close','Escalate']},
    Governance:{title:'Portfolio Governance',singular:'Governance Event',description:'Reviews, decisions and portfolio control events.',primaryAction:'Schedule Review',records:[{id:'gov-01',name:'Monthly portfolio review',context:'Executive portfolio health and decisions',owner:'Neo Morake',status:'Scheduled',updated:'28 Aug 2026'},{id:'gov-02',name:'Benefits baseline approval',context:'Approve revised value assumptions',owner:'Zanele Khumalo',status:'Pending',updated:'04 Sep 2026'}],fields:commonFields('Governance Event'),contextualActions:['Request Approval']},
    Activity:{title:'Portfolio Activity',singular:'Activity Note',description:'Decisions, updates and controlled portfolio history.',primaryAction:'Add Note',records:[{id:'act-01',name:'Portfolio health reviewed',context:'Health remains Watch due to vendor exposure',owner:'Neo Morake',status:'Recorded',updated:'Today'},{id:'act-02',name:'Programme moved',context:'Policy Control moved into Strategic Transformation',owner:'Mia Daniels',status:'Recorded',updated:'Yesterday'}],fields:commonFields('Activity Note')},
  }
  return <RecordCollectionWorkspace config={configs[tab]}/>
}

function PortfolioSettings({onArchive}:{onArchive:()=>void}) { return <div className="grid gap-5 xl:grid-cols-2"><SectionCard title="Visibility & access" description="Control who can find and open this portfolio."><div className="space-y-4 p-5"><Setting label="Visibility" value="Organization"/><Setting label="Default member access" value="Read only"/><Setting label="Restricted documents" value="Members only"/></div></SectionCard><SectionCard title="Default governance" description="Controls applied to new programmes and projects."><div className="space-y-4 p-5"><Toggle label="Monthly portfolio review"/><Toggle label="Benefits baseline approval"/><Toggle label="Risk escalation threshold"/></div></SectionCard><SectionCard title="Archive portfolio" description="Remove this portfolio from active delivery views." className="xl:col-span-2"><div className="flex flex-wrap items-center justify-between gap-4 p-5"><p className="max-w-2xl text-sm text-muted-foreground">Programmes and projects remain available. The portfolio can be restored from the archived register.</p><button type="button" onClick={onArchive} className="inline-flex items-center gap-2 rounded-lg border border-destructive/30 px-4 py-2 text-sm font-semibold text-destructive"><Archive className="size-4"/>Archive Portfolio</button></div></SectionCard></div> }

function Detail({label,value}:{label:string;value:string}) { return <div><p className="text-[0.65rem] font-semibold tracking-wide text-muted-foreground uppercase">{label}</p><p className="mt-1 text-sm font-medium">{value}</p></div> }
function Owner({icon:Icon,label,value}:{icon:typeof Users;label:string;value:string}) { return <div className="flex items-center gap-3"><span className="flex size-9 items-center justify-center rounded-lg bg-muted"><Icon className="size-4"/></span><div><p className="text-xs text-muted-foreground">{label}</p><p className="text-sm font-semibold">{value}</p></div></div> }
function Setting({label,value}:{label:string;value:string}) { return <label><span className="text-sm font-medium">{label}</span><select defaultValue={value} className="mt-1.5 h-11 w-full rounded-lg border border-border bg-background px-3 text-sm"><option>{value}</option><option>Members only</option><option>Restricted</option></select></label> }
function Toggle({label}:{label:string}) { return <label className="flex items-center justify-between rounded-xl border border-border p-4 text-sm font-medium"><span>{label}</span><input type="checkbox" defaultChecked className="size-4"/></label> }
