'use client'

import { WorkspaceHeader } from '@/components/shared/workspace-header'
import { RecordCollectionWorkspace } from '@/features/product-ui/components/record-collection-workspace'
import { deliveryProjects } from '../data'
import { MetricCard, SectionCard } from './delivery-primitives'

const projectMetrics=[['Active Projects','36','+4 this quarter'],['At Risk','7','2 critical'],['Upcoming Gates','12','Next 30 days'],['Pending Approvals','18','5 overdue'],['Vendor Dependencies','27','12 critical'],['On-Time Delivery','84%','+6% this quarter']] as const

export function ProjectsScreen(){const records=deliveryProjects.map((project)=>({id:project.id,name:project.name,context:project.framework,framework:project.framework,phase:project.phase,owner:project.owner,status:project.health,nextGate:project.nextGate,due:project.dueDate,progress:`${project.progress}%`,portfolio:'Strategic Transformation',programme:project.name.includes('Claims')?'Claims Modernisation':'Digital Onboarding',updated:'Today'}));return <><WorkspaceHeader category="Delivery" title="Projects" description="Govern and track delivery across active initiatives." action="New Project" actionHref="/operations/projects/new"/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 2xl:grid-cols-6">{projectMetrics.map(([label,value,detail])=><MetricCard key={label} label={label} value={value} detail={detail}/>)}</div><div className="mt-5"><RecordCollectionWorkspace config={{title:'Project Register',singular:'Project',description:'Governed initiatives across portfolios and programmes.',primaryAction:'New Project',records,recordHref:(record)=>`/operations/projects/${record.id}`,filters:['Portfolio','Programme','Framework','Owner','Health','Due Date'],columns:[{id:'name',label:'Project'},{id:'portfolio',label:'Portfolio'},{id:'programme',label:'Programme'},{id:'framework',label:'Framework'},{id:'phase',label:'Phase'},{id:'status',label:'Health'},{id:'owner',label:'Owner'},{id:'nextGate',label:'Next Gate'},{id:'due',label:'Due Date'}],fields:[{id:'name',label:'Project Name',required:true},{id:'context',label:'Description',type:'textarea',required:true},{id:'owner',label:'Owner',type:'select',options:['Neo Morake','Amara Dlamini','Thabo Mokoena','Naledi Maseko']},{id:'status',label:'Status',type:'select',options:['Planning','On Track','At Risk','On Hold','Complete']},{id:'portfolio',label:'Portfolio'},{id:'programme',label:'Programme'},{id:'framework',label:'Framework'},{id:'due',label:'Due Date',type:'date'}],contextualActions:['Assign Owner','Change Status','Move to Portfolio','Move to Programme'],emptyDescription:'Create the first governed project to begin delivery planning.'}}/></div><div className="mt-5 grid gap-5 xl:grid-cols-3"><SummaryPanel title="Portfolio health" value="82%" detail="Controlled · improving" items={['29 projects on track','5 projects at risk','2 critical projects']}/><SummaryPanel title="Upcoming gates" value="12" detail="Due in the next 30 days" items={['UAT Sign-off · Today','Design Authority · 28 Aug','Go-live Readiness · 04 Sep']}/><SummaryPanel title="Recent project activity" value="24" detail="Updates today" items={['UAT evidence uploaded','Vendor dependency escalated','Business case approved']}/></div></>}

function SummaryPanel({title,value,detail,items}:{title:string;value:string;detail:string;items:string[]}){return <SectionCard title={title}><div className="p-5"><p className="text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p><div className="mt-5 divide-y divide-border border-t border-border">{items.map((item)=><p key={item} className="py-2.5 text-xs font-medium">{item}</p>)}</div></div></SectionCard>}
