'use client'

import { CheckCircle2 } from 'lucide-react'
import Link from 'next/link'
import { useState } from 'react'

import { WorkspaceHeader } from '@/components/shared/workspace-header'

export function VendorForm({ mode = 'create', vendorId }: { mode?: 'create'|'edit'; vendorId?:string }) {
  const [saved,setSaved] = useState(false)
  if (saved) return <><WorkspaceHeader category="Delivery" parent={{label:'Vendors',href:'/delivery/vendors'}} title={mode === 'create' ? 'New Vendor' : 'Edit Vendor'} /><div className="mx-auto max-w-xl rounded-xl border border-success/25 bg-card p-10 text-center"><CheckCircle2 className="mx-auto size-10 text-success" /><h2 className="mt-4 text-xl font-bold">Vendor {mode === 'create' ? 'created' : 'updated'}</h2><p className="mt-2 text-sm text-muted-foreground">The vendor workspace and governance profile are ready.</p><Link href={vendorId ? `/delivery/vendors/${vendorId}` : '/delivery/vendors/twilio-whatsapp-api'} className="mt-6 inline-flex rounded-lg bg-brand px-4 py-2.5 text-sm font-semibold text-white">Open vendor</Link></div></>
  return <><WorkspaceHeader category="Delivery" parent={{label:'Vendors',href:'/delivery/vendors'}} title={mode === 'create' ? 'New Vendor' : 'Edit Vendor'} description="Create and govern a third-party delivery relationship." /><form onSubmit={(event) => { event.preventDefault(); setSaved(true) }} className="mx-auto max-w-5xl space-y-5"><FormSection title="Vendor information" description="Core identity and service classification."><Field label="Vendor name" placeholder="Vendor legal or trading name" required /><Field label="Vendor type" options={['Technology','Integration','Data','Infrastructure','Compliance','Operations','Creative','Other']} /><Field label="Service category" placeholder="WhatsApp API" /><Field label="Region" placeholder="South Africa" /></FormSection><FormSection title="Ownership & contacts" description="Accountability for the vendor relationship."><Field label="Account owner" options={['Lethabo Nkosi','Naledi Maseko','Zanele Khumalo','Amara Dlamini']} /><Field label="Primary contact" placeholder="Full name" /><Field label="Contact email" type="email" placeholder="contact@vendor.com" /><Field label="Phone" type="tel" placeholder="+27" /></FormSection><FormSection title="Commercial & risk" description="Contract, SLA and compliance position."><Field label="Contract start" type="date" /><Field label="Contract end" type="date" /><Field label="Contract value" placeholder="R0.00" /><Field label="Renewal notice" options={['30 days','60 days','90 days','120 days']} /><Field label="SLA level" placeholder="99.9% availability" /><Field label="Data sensitivity" options={['Low','Moderate','High','Restricted']} /><Field label="Risk level" options={['Low','Medium','High','Critical']} /><Field label="Compliance status" options={['Current','Review due','Gap open','Not assessed']} /></FormSection><footer className="flex items-center justify-end gap-2 rounded-xl border border-border bg-card p-4"><Link href="/delivery/vendors" className="rounded-lg border border-border px-4 py-2 text-sm font-semibold">Cancel</Link><button type="submit" className="rounded-lg bg-brand px-4 py-2 text-sm font-semibold text-white">Save Vendor</button></footer></form></>
}
function FormSection({ title,description,children }: { title:string;description:string;children:React.ReactNode }) { return <section className="rounded-xl border border-border bg-card p-6"><h2 className="text-lg font-semibold">{title}</h2><p className="mt-1 text-sm text-muted-foreground">{description}</p><div className="mt-6 grid gap-5 md:grid-cols-2">{children}</div></section> }
function Field({ label,placeholder,options,type='text',required }: { label:string;placeholder?:string;options?:string[];type?:string;required?:boolean }) { return <label className="text-sm font-medium">{label}{required ? <span className="text-danger"> *</span> : null}{options ? <select className="mt-1.5 h-11 w-full rounded-lg border border-border bg-background px-3 text-sm">{options.map((option) => <option key={option}>{option}</option>)}</select> : <input type={type} required={required} placeholder={placeholder} className="mt-1.5 h-11 w-full rounded-lg border border-border bg-background px-3 text-sm" />}</label> }
