create schema if not exists private;
revoke all on schema private from public, anon, authenticated;

create table public.documents (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  display_name text not null check (length(trim(display_name)) > 0),
  storage_bucket text not null default 'documents' check (storage_bucket = 'documents'),
  storage_path text not null,
  mime_type text not null,
  file_size bigint not null check (file_size > 0 and file_size <= 52428800),
  classification text not null default 'Project Evidence'
    check (classification in ('Project Evidence','Requirements','Compliance','Design Artefact','Commercial','Other')),
  confidentiality text not null default 'Internal'
    check (confidentiality in ('Internal','Confidential','Restricted')),
  linked_record_type text,
  linked_record_id uuid,
  linked_path text,
  description text,
  version integer not null default 1 check (version > 0),
  uploaded_by uuid default auth.uid() references auth.users(id) on delete set null,
  archived_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, storage_path),
  unique (id, organization_id)
);

create index documents_org_created_idx
  on public.documents(organization_id, created_at desc)
  where archived_at is null;
create index documents_linked_record_idx
  on public.documents(organization_id, linked_record_type, linked_record_id)
  where archived_at is null;
create index documents_uploaded_by_idx on public.documents(uploaded_by);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  title text not null check (length(trim(title)) > 0),
  body text,
  category text not null default 'System'
    check (category in ('System','Delivery','Operations','Commercial','Finance','Support','Documents','Import')),
  href text check (href is null or (href like '/%' and href not like '//%')),
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index notifications_inbox_idx
  on public.notifications(user_id, organization_id, read_at, created_at desc);
create index notifications_org_idx on public.notifications(organization_id);

create table public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number bigint generated by default as identity unique,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  submitted_by uuid not null default auth.uid() references auth.users(id) on delete restrict,
  subject text not null check (length(trim(subject)) between 3 and 160),
  category text not null default 'General'
    check (category in ('General','Access','Data','Delivery','Billing','Technical')),
  priority text not null default 'Medium'
    check (priority in ('Low','Medium','High','Critical')),
  description text not null check (length(trim(description)) between 10 and 5000),
  status text not null default 'Open'
    check (status in ('Open','In Progress','Waiting on Customer','Resolved','Closed')),
  resolution text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, organization_id)
);

create index support_tickets_org_status_idx
  on public.support_tickets(organization_id, status, updated_at desc);
create index support_tickets_submitted_by_idx on public.support_tickets(submitted_by);

create table public.data_import_jobs (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  collection text not null,
  file_name text not null,
  file_type text not null check (file_type in ('csv','xlsx')),
  status text not null check (status in ('Completed','Completed with warnings','Failed')),
  row_count integer not null check (row_count >= 0),
  imported_count integer not null check (imported_count >= 0),
  skipped_count integer not null check (skipped_count >= 0),
  errors jsonb not null default '[]'::jsonb check (jsonb_typeof(errors) = 'array'),
  created_by uuid not null default auth.uid() references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index data_import_jobs_org_created_idx
  on public.data_import_jobs(organization_id, created_at desc);
create index data_import_jobs_created_by_idx on public.data_import_jobs(created_by);

create table public.record_index (
  organization_id uuid not null references public.organizations(id) on delete cascade,
  resource text not null,
  record_id uuid not null,
  title text not null,
  subtitle text not null default '',
  href text not null check (href like '/%' and href not like '//%'),
  updated_at timestamptz not null default now(),
  search_vector tsvector generated always as (
    setweight(to_tsvector('simple', coalesce(title, '')), 'A') ||
    setweight(to_tsvector('simple', coalesce(subtitle, '')), 'B')
  ) stored,
  primary key (organization_id, resource, record_id)
);

create index record_index_search_idx on public.record_index using gin(search_vector);
create index record_index_org_updated_idx on public.record_index(organization_id, updated_at desc);

create table public.record_change_events (
  id bigint generated always as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  resource text not null,
  record_id uuid not null,
  operation text not null check (operation in ('INSERT','UPDATE','DELETE')),
  actor_id uuid references auth.users(id) on delete set null,
  changed_at timestamptz not null default now()
);

create index record_change_events_org_idx
  on public.record_change_events(organization_id, id desc);
create index record_change_events_actor_idx on public.record_change_events(actor_id);

alter table public.documents enable row level security;
alter table public.notifications enable row level security;
alter table public.support_tickets enable row level security;
alter table public.data_import_jobs enable row level security;
alter table public.record_index enable row level security;
alter table public.record_change_events enable row level security;

create policy documents_select on public.documents for select to authenticated
  using ((select public.is_member_of(organization_id)));
create policy documents_insert on public.documents for insert to authenticated
  with check ((select public.is_member_of(organization_id)) and uploaded_by = (select auth.uid()));
create policy documents_update on public.documents for update to authenticated
  using ((select public.is_member_of(organization_id)))
  with check ((select public.is_member_of(organization_id)));

create policy notifications_select on public.notifications for select to authenticated
  using (user_id = (select auth.uid()) and (select public.is_member_of(organization_id)));
create policy notifications_insert on public.notifications for insert to authenticated
  with check (user_id = (select auth.uid()) and (select public.is_member_of(organization_id)));
create policy notifications_update on public.notifications for update to authenticated
  using (user_id = (select auth.uid()) and (select public.is_member_of(organization_id)))
  with check (user_id = (select auth.uid()) and (select public.is_member_of(organization_id)));
create policy notifications_delete on public.notifications for delete to authenticated
  using (user_id = (select auth.uid()) and (select public.is_member_of(organization_id)));

create policy support_tickets_select on public.support_tickets for select to authenticated
  using ((select public.is_member_of(organization_id)));
create policy support_tickets_insert on public.support_tickets for insert to authenticated
  with check (submitted_by = (select auth.uid()) and (select public.is_member_of(organization_id)));
create policy support_tickets_update on public.support_tickets for update to authenticated
  using (
    (select public.is_member_of(organization_id)) and
    (submitted_by = (select auth.uid()) or (select public.has_role(organization_id, array['owner','admin'])))
  )
  with check ((select public.is_member_of(organization_id)));

create policy data_import_jobs_select on public.data_import_jobs for select to authenticated
  using ((select public.is_member_of(organization_id)));
create policy data_import_jobs_insert on public.data_import_jobs for insert to authenticated
  with check (created_by = (select auth.uid()) and (select public.is_member_of(organization_id)));

create policy record_index_select on public.record_index for select to authenticated
  using ((select public.is_member_of(organization_id)));
create policy record_change_events_select on public.record_change_events for select to authenticated
  using ((select public.is_member_of(organization_id)));

create trigger documents_set_updated_at before update on public.documents
  for each row execute function public.set_updated_at();
create trigger support_tickets_set_updated_at before update on public.support_tickets
  for each row execute function public.set_updated_at();
create trigger documents_audit after insert or update or delete on public.documents
  for each row execute function public.record_audit_event();
create trigger support_tickets_audit after insert or update or delete on public.support_tickets
  for each row execute function public.record_audit_event();
create trigger data_import_jobs_audit after insert or update or delete on public.data_import_jobs
  for each row execute function public.record_audit_event();

create or replace function private.index_record_change() returns trigger
language plpgsql security definer set search_path = ''
as $$
declare
  payload jsonb;
  target_org uuid;
  target_id uuid;
  target_title text;
  target_subtitle text;
  target_href text;
  archived boolean;
begin
  if auth.uid() is null and current_user not in ('postgres', 'service_role') then
    raise insufficient_privilege using message = 'An authenticated database role is required';
  end if;

  payload := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  target_org := (payload ->> 'organization_id')::uuid;
  target_id := (payload ->> 'id')::uuid;
  archived := coalesce(payload ->> 'archived_at', '') <> '';

  case tg_table_name
    when 'clients' then
      target_title := payload ->> 'name';
      target_subtitle := concat_ws(' · ', payload ->> 'industry', payload ->> 'contact_name', payload ->> 'status');
      target_href := '/operations/clients/' || target_id;
    when 'frameworks' then
      target_title := payload ->> 'name';
      target_subtitle := concat_ws(' · ', payload ->> 'type', payload ->> 'version');
      target_href := '/delivery/frameworks/' || target_id;
    when 'projects' then
      target_title := payload ->> 'name';
      target_subtitle := concat_ws(' · ', payload ->> 'status', payload ->> 'health', payload ->> 'next_gate');
      target_href := '/operations/projects/' || target_id;
    when 'portfolios' then
      target_title := payload ->> 'name';
      target_subtitle := concat_ws(' · ', payload ->> 'code', payload ->> 'status');
      target_href := '/delivery/portfolio/' || target_id;
    when 'programmes' then
      target_title := payload ->> 'name';
      target_subtitle := concat_ws(' · ', payload ->> 'code', payload ->> 'status', payload ->> 'health');
      target_href := '/delivery/portfolio/' || (payload ->> 'portfolio_id') || '/programmes/' || target_id;
    when 'approvals' then
      target_title := payload ->> 'title';
      target_subtitle := concat_ws(' · ', payload ->> 'priority', payload ->> 'status', payload ->> 'description');
      target_href := '/delivery/approvals/' || target_id;
    when 'team_members' then
      target_title := payload ->> 'full_name';
      target_subtitle := concat_ws(' · ', payload ->> 'email', payload ->> 'job_title', payload ->> 'delivery_role');
      target_href := '/people/team/' || target_id;
    when 'client_onboardings' then
      target_title := payload ->> 'client_name';
      target_subtitle := concat_ws(' · ', payload ->> 'stage', payload ->> 'health', payload ->> 'status');
      target_href := '/operations/onboarding/' || target_id;
    when 'vendors' then
      target_title := payload ->> 'name';
      target_subtitle := concat_ws(' · ', payload ->> 'vendor_type', payload ->> 'service_category', payload ->> 'status');
      target_href := '/delivery/vendors/' || target_id;
    when 'tasks' then
      target_title := payload ->> 'title';
      target_subtitle := concat_ws(' · ', payload ->> 'priority', payload ->> 'status', payload ->> 'description');
      target_href := '/operations/tasks/' || target_id;
    when 'calendar_events' then
      target_title := payload ->> 'title';
      target_subtitle := concat_ws(' · ', payload ->> 'event_type', payload ->> 'location', payload ->> 'status');
      target_href := '/operations/calendar/' || target_id;
    when 'leads' then
      target_title := payload ->> 'company_name';
      target_subtitle := concat_ws(' · ', payload ->> 'contact_name', payload ->> 'contact_email', payload ->> 'status');
      target_href := '/commercial/leads/' || target_id;
    when 'sales_opportunities' then
      target_title := payload ->> 'name';
      target_subtitle := concat_ws(' · ', payload ->> 'client_name', payload ->> 'stage');
      target_href := '/commercial/sales/' || target_id;
    when 'quotes' then
      target_title := payload ->> 'quote_number';
      target_subtitle := concat_ws(' · ', payload ->> 'client_name', payload ->> 'status');
      target_href := '/commercial/quotes/' || target_id;
    when 'invoices' then
      target_title := payload ->> 'invoice_number';
      target_subtitle := concat_ws(' · ', payload ->> 'client_name', payload ->> 'status');
      target_href := '/finance/invoices/' || target_id;
    when 'expenses' then
      target_title := payload ->> 'description';
      target_subtitle := concat_ws(' · ', payload ->> 'category', payload ->> 'vendor_name', payload ->> 'status');
      target_href := '/finance/expenses/' || target_id;
    when 'financial_forecasts' then
      target_title := payload ->> 'name';
      target_subtitle := concat_ws(' · ', payload ->> 'period_label', payload ->> 'forecast_type', payload ->> 'status');
      target_href := '/finance/forecast/' || target_id;
    when 'documents' then
      target_title := payload ->> 'display_name';
      target_subtitle := concat_ws(' · ', payload ->> 'classification', payload ->> 'confidentiality', payload ->> 'description');
      target_href := '/api/documents/' || target_id || '/download';
    when 'support_tickets' then
      target_title := 'SUP-' || lpad(payload ->> 'ticket_number', 6, '0') || ' · ' || (payload ->> 'subject');
      target_subtitle := concat_ws(' · ', payload ->> 'category', payload ->> 'priority', payload ->> 'status');
      target_href := '/support/' || target_id;
    else
      raise exception 'Unsupported search resource: %', tg_table_name;
  end case;

  if tg_op = 'DELETE' or archived then
    delete from public.record_index
      where organization_id = target_org and resource = tg_table_name and record_id = target_id;
  else
    insert into public.record_index(organization_id, resource, record_id, title, subtitle, href, updated_at)
    values (
      target_org,
      tg_table_name,
      target_id,
      coalesce(target_title, 'Untitled record'),
      coalesce(target_subtitle, ''),
      target_href,
      coalesce((payload ->> 'updated_at')::timestamptz, (payload ->> 'created_at')::timestamptz, now())
    )
    on conflict (organization_id, resource, record_id) do update set
      title = excluded.title,
      subtitle = excluded.subtitle,
      href = excluded.href,
      updated_at = excluded.updated_at;
  end if;

  insert into public.record_change_events(organization_id, resource, record_id, operation, actor_id)
  values (target_org, tg_table_name, target_id, tg_op, auth.uid());

  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

revoke execute on function private.index_record_change() from public, anon, authenticated, service_role;

do $$
declare
  source_table text;
begin
  foreach source_table in array array[
    'clients','frameworks','projects','portfolios','programmes','approvals',
    'team_members','client_onboardings','vendors','tasks','calendar_events',
    'leads','sales_opportunities','quotes','invoices','expenses','financial_forecasts',
    'documents','support_tickets'
  ]
  loop
    execute format(
      'create trigger %I_search_realtime after insert or update or delete on public.%I for each row execute function private.index_record_change()',
      source_table,
      source_table
    );
  end loop;
end;
$$;

insert into public.record_index(organization_id, resource, record_id, title, subtitle, href, updated_at)
select organization_id, 'clients', id, name, concat_ws(' · ', industry, contact_name, status), '/operations/clients/' || id, updated_at from public.clients where archived_at is null
union all select organization_id, 'frameworks', id, name, concat_ws(' · ', type, version), '/delivery/frameworks/' || id, updated_at from public.frameworks where archived_at is null
union all select organization_id, 'projects', id, name, concat_ws(' · ', status, health, next_gate), '/operations/projects/' || id, updated_at from public.projects where archived_at is null
union all select organization_id, 'portfolios', id, name, concat_ws(' · ', code, status), '/delivery/portfolio/' || id, updated_at from public.portfolios where archived_at is null
union all select organization_id, 'programmes', id, name, concat_ws(' · ', code, status, health), '/delivery/portfolio/' || portfolio_id || '/programmes/' || id, updated_at from public.programmes where archived_at is null
union all select organization_id, 'approvals', id, title, concat_ws(' · ', priority, status, description), '/delivery/approvals/' || id, updated_at from public.approvals
union all select organization_id, 'team_members', id, full_name, concat_ws(' · ', email, job_title, delivery_role), '/people/team/' || id, updated_at from public.team_members where archived_at is null
union all select organization_id, 'client_onboardings', id, client_name, concat_ws(' · ', stage, health, status), '/operations/onboarding/' || id, updated_at from public.client_onboardings where archived_at is null
union all select organization_id, 'vendors', id, name, concat_ws(' · ', vendor_type, service_category, status), '/delivery/vendors/' || id, updated_at from public.vendors where archived_at is null
union all select organization_id, 'tasks', id, title, concat_ws(' · ', priority, status, description), '/operations/tasks/' || id, updated_at from public.tasks where archived_at is null
union all select organization_id, 'calendar_events', id, title, concat_ws(' · ', event_type, location, status), '/operations/calendar/' || id, updated_at from public.calendar_events where archived_at is null
union all select organization_id, 'leads', id, company_name, concat_ws(' · ', contact_name, contact_email, status), '/commercial/leads/' || id, updated_at from public.leads where archived_at is null
union all select organization_id, 'sales_opportunities', id, name, concat_ws(' · ', client_name, stage), '/commercial/sales/' || id, updated_at from public.sales_opportunities where archived_at is null
union all select organization_id, 'quotes', id, quote_number, concat_ws(' · ', client_name, status), '/commercial/quotes/' || id, updated_at from public.quotes where archived_at is null
union all select organization_id, 'invoices', id, invoice_number, concat_ws(' · ', client_name, status), '/finance/invoices/' || id, updated_at from public.invoices where archived_at is null
union all select organization_id, 'expenses', id, description, concat_ws(' · ', category, vendor_name, status), '/finance/expenses/' || id, updated_at from public.expenses where archived_at is null
union all select organization_id, 'financial_forecasts', id, name, concat_ws(' · ', period_label, forecast_type, status), '/finance/forecast/' || id, updated_at from public.financial_forecasts where archived_at is null;

create or replace function public.search_organization_records(
  target_organization uuid,
  search_query text,
  result_limit integer default 20
)
returns table (
  resource text,
  record_id uuid,
  title text,
  subtitle text,
  href text,
  updated_at timestamptz,
  rank real
)
language sql stable security invoker set search_path = ''
as $$
  with normalized as (
    select string_agg(quote_literal(term) || ':*', ' & ') as expression
    from regexp_split_to_table(lower(trim(search_query)), '[^[:alnum:]_-]+') as term
    where length(term) >= 2
  ), query as (
    select to_tsquery('simple', expression) as value
    from normalized
    where expression is not null
  )
  select
    records.resource,
    records.record_id,
    records.title,
    records.subtitle,
    records.href,
    records.updated_at,
    ts_rank(records.search_vector, query.value)::real as rank
  from public.record_index records
  cross join query
  where records.organization_id = target_organization
    and records.search_vector @@ query.value
  order by rank desc, records.updated_at desc
  limit least(greatest(coalesce(result_limit, 20), 1), 50);
$$;

revoke all on function public.search_organization_records(uuid, text, integer) from public, anon;
grant execute on function public.search_organization_records(uuid, text, integer) to authenticated;

insert into storage.buckets(id, name, public, file_size_limit, allowed_mime_types)
values (
  'documents',
  'documents',
  false,
  52428800,
  array[
    'application/pdf',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'text/csv',
    'image/png',
    'image/jpeg'
  ]::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy documents_objects_select on storage.objects for select to authenticated
using (
  bucket_id = 'documents' and exists (
    select 1 from public.memberships membership
    where membership.user_id = (select auth.uid())
      and membership.status = 'active'
      and membership.organization_id::text = (storage.foldername(name))[1]
  )
);
create policy documents_objects_insert on storage.objects for insert to authenticated
with check (
  bucket_id = 'documents' and exists (
    select 1 from public.memberships membership
    where membership.user_id = (select auth.uid())
      and membership.status = 'active'
      and membership.organization_id::text = (storage.foldername(name))[1]
  )
);
create policy documents_objects_update on storage.objects for update to authenticated
using (
  bucket_id = 'documents' and exists (
    select 1 from public.memberships membership
    where membership.user_id = (select auth.uid())
      and membership.status = 'active'
      and membership.organization_id::text = (storage.foldername(name))[1]
  )
)
with check (
  bucket_id = 'documents' and exists (
    select 1 from public.memberships membership
    where membership.user_id = (select auth.uid())
      and membership.status = 'active'
      and membership.organization_id::text = (storage.foldername(name))[1]
  )
);
create policy documents_objects_delete on storage.objects for delete to authenticated
using (
  bucket_id = 'documents' and exists (
    select 1 from public.memberships membership
    where membership.user_id = (select auth.uid())
      and membership.status = 'active'
      and membership.organization_id::text = (storage.foldername(name))[1]
  )
);

do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'record_change_events'
    ) then
      alter publication supabase_realtime add table public.record_change_events;
    end if;
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'notifications'
    ) then
      alter publication supabase_realtime add table public.notifications;
    end if;
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'documents'
    ) then
      alter publication supabase_realtime add table public.documents;
    end if;
  end if;
end;
$$;

revoke all on
  public.documents,
  public.notifications,
  public.support_tickets,
  public.data_import_jobs,
  public.record_index,
  public.record_change_events
from anon;

grant select, insert, update on public.documents to authenticated;
grant select, insert, update, delete on public.notifications to authenticated;
grant select, insert, update on public.support_tickets to authenticated;
grant select, insert on public.data_import_jobs to authenticated;
grant select on public.record_index, public.record_change_events to authenticated;
grant usage, select on sequence public.support_tickets_ticket_number_seq to authenticated;
