-- Phase 7: platform administration.
-- Phase 8: tenant integrations, automations, scheduling and durable jobs.

create schema if not exists private;

create or replace function public.is_himark_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.memberships m
    join public.organizations o on o.id = m.organization_id
    where m.user_id = (select auth.uid())
      and m.status = 'active'
      and m.role_id in ('owner', 'admin')
      and o.slug = 'himark'
      and o.status = 'active'
  );
$$;

revoke all on function public.is_himark_admin() from public, anon;
grant execute on function public.is_himark_admin() to authenticated, service_role;

create table public.tenant_configurations (
  organization_id uuid primary key references public.organizations(id) on delete cascade,
  operating_model text not null default 'hybrid'
    check (operating_model in ('centralized', 'federated', 'hybrid')),
  default_currency text not null default 'ZAR'
    check (default_currency ~ '^[A-Z]{3}$'),
  timezone text not null default 'Africa/Johannesburg'
    check (length(trim(timezone)) between 3 and 80),
  data_region text not null default 'South Africa'
    check (length(trim(data_region)) between 2 and 80),
  retention_days integer not null default 2555
    check (retention_days between 30 and 3650),
  approval_escalation_hours integer not null default 48
    check (approval_escalation_hours between 1 and 2160),
  evidence_required boolean not null default true,
  project_visibility text not null default 'organization'
    check (project_visibility in ('organization', 'restricted')),
  strategic_objectives text[] not null default '{}',
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.platform_subscriptions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null unique references public.organizations(id) on delete cascade,
  plan_key text not null check (plan_key in ('core', 'framework', 'enterprise', 'strategic-enterprise')),
  status text not null default 'draft'
    check (status in ('draft', 'pending', 'active', 'paused', 'cancelled', 'expired')),
  billing_cycle text not null default 'annual'
    check (billing_cycle in ('monthly', 'annual', 'custom')),
  seat_limit integer not null default 10 check (seat_limit between 1 and 100000),
  starts_on date,
  renews_on date,
  amount numeric(14,2) not null default 0 check (amount >= 0),
  currency text not null default 'ZAR' check (currency ~ '^[A-Z]{3}$'),
  billing_email text check (billing_email is null or position('@' in billing_email) > 1),
  notes text check (notes is null or length(notes) <= 5000),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (renews_on is null or starts_on is null or renews_on >= starts_on)
);

create index platform_subscriptions_status_idx
  on public.platform_subscriptions(status, renews_on);

create table public.subscription_events (
  id bigint generated always as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  subscription_id uuid not null references public.platform_subscriptions(id) on delete cascade,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null check (action in ('created', 'updated', 'paused', 'resumed', 'cancelled')),
  old_value jsonb,
  new_value jsonb,
  created_at timestamptz not null default now()
);

create index subscription_events_subscription_idx
  on public.subscription_events(subscription_id, created_at desc);
create index subscription_events_org_idx
  on public.subscription_events(organization_id, created_at desc);

create table public.support_cases (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  support_ticket_id uuid unique,
  case_number bigint generated by default as identity unique,
  subject text not null check (length(trim(subject)) between 3 and 160),
  category text not null default 'General'
    check (category in ('General', 'Access', 'Data', 'Delivery', 'Billing', 'Technical')),
  priority text not null default 'Medium'
    check (priority in ('Low', 'Medium', 'High', 'Critical')),
  status text not null default 'Open'
    check (status in ('Open', 'Investigating', 'Waiting on Customer', 'Resolved', 'Closed')),
  assignee_name text check (assignee_name is null or length(trim(assignee_name)) between 2 and 120),
  sla_due_at timestamptz,
  internal_notes text check (internal_notes is null or length(internal_notes) <= 10000),
  resolution text check (resolution is null or length(resolution) <= 10000),
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, organization_id),
  foreign key (support_ticket_id, organization_id)
    references public.support_tickets(id, organization_id) on delete set null (support_ticket_id)
);

create index support_cases_org_status_idx
  on public.support_cases(organization_id, status, priority, updated_at desc);
create index support_cases_sla_idx
  on public.support_cases(sla_due_at) where status not in ('Resolved', 'Closed');

create table public.knowledge_articles (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  title text not null check (length(trim(title)) between 3 and 180),
  slug text not null check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  summary text check (summary is null or length(summary) <= 500),
  content text not null check (length(trim(content)) between 10 and 50000),
  category text not null default 'Guide'
    check (category in ('Guide', 'Policy', 'Procedure', 'FAQ', 'Release Note', 'Troubleshooting')),
  visibility text not null default 'organization'
    check (visibility in ('organization', 'internal')),
  status text not null default 'draft'
    check (status in ('draft', 'published', 'archived')),
  tags text[] not null default '{}',
  version integer not null default 1 check (version > 0),
  published_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  updated_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, slug),
  unique (id, organization_id),
  check ((status = 'published' and published_at is not null) or status <> 'published')
);

create index knowledge_articles_org_status_idx
  on public.knowledge_articles(organization_id, status, updated_at desc);
create index knowledge_articles_tags_idx
  on public.knowledge_articles using gin(tags);

create table public.integration_connections (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  name text not null check (length(trim(name)) between 2 and 120),
  provider text not null default 'Webhook'
    check (length(trim(provider)) between 2 and 80),
  status text not null default 'pending'
    check (status in ('pending', 'connected', 'disabled', 'error')),
  event_key text not null default '*'
    check (event_key = '*' or event_key ~ '^[a-z0-9][a-z0-9._-]{1,79}$'),
  secret_hint text,
  last_event_at timestamptz,
  last_error text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, organization_id)
);

create index integration_connections_org_status_idx
  on public.integration_connections(organization_id, status, updated_at desc);

create table private.integration_secrets (
  connection_id uuid primary key references public.integration_connections(id) on delete cascade,
  secret_hash bytea not null,
  rotated_at timestamptz not null default now()
);

revoke all on private.integration_secrets from public, anon, authenticated;

create table public.integration_events (
  id bigint generated always as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  connection_id uuid not null,
  event_key text not null,
  external_id text,
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  status text not null default 'accepted'
    check (status in ('accepted', 'processed', 'ignored', 'failed')),
  received_at timestamptz not null default now(),
  foreign key (connection_id, organization_id)
    references public.integration_connections(id, organization_id) on delete cascade
);

create index integration_events_org_time_idx
  on public.integration_events(organization_id, received_at desc);
create index integration_events_connection_idx
  on public.integration_events(connection_id, received_at desc);
create unique index integration_events_external_id_idx
  on public.integration_events(connection_id, external_id) where external_id is not null;

create table public.automation_rules (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  integration_connection_id uuid,
  name text not null check (length(trim(name)) between 2 and 120),
  description text check (description is null or length(description) <= 1000),
  trigger_type text not null default 'manual'
    check (trigger_type in ('manual', 'schedule', 'integration_event')),
  trigger_config jsonb not null default '{}'::jsonb check (jsonb_typeof(trigger_config) = 'object'),
  action_type text not null default 'notification' check (action_type = 'notification'),
  action_config jsonb not null default '{}'::jsonb check (jsonb_typeof(action_config) = 'object'),
  status text not null default 'draft'
    check (status in ('draft', 'active', 'paused')),
  created_by uuid references auth.users(id) on delete set null,
  run_count bigint not null default 0 check (run_count >= 0),
  last_run_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, organization_id),
  foreign key (integration_connection_id, organization_id)
    references public.integration_connections(id, organization_id) on delete set null (integration_connection_id),
  check ((trigger_type = 'integration_event' and integration_connection_id is not null) or trigger_type <> 'integration_event')
);

create index automation_rules_org_status_idx
  on public.automation_rules(organization_id, status, updated_at desc);
create index automation_rules_connection_idx
  on public.automation_rules(integration_connection_id, status)
  where integration_connection_id is not null;

create table public.automation_schedules (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  rule_id uuid not null unique,
  interval_minutes integer not null check (interval_minutes between 5 and 525600),
  timezone text not null default 'Africa/Johannesburg',
  next_run_at timestamptz not null,
  enabled boolean not null default true,
  last_enqueued_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (rule_id, organization_id)
    references public.automation_rules(id, organization_id) on delete cascade
);

create index automation_schedules_due_idx
  on public.automation_schedules(next_run_at, organization_id) where enabled;
create index automation_schedules_org_idx
  on public.automation_schedules(organization_id, enabled);

create table public.automation_runs (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  rule_id uuid not null,
  integration_event_id bigint references public.integration_events(id) on delete set null,
  trigger_type text not null check (trigger_type in ('manual', 'schedule', 'integration_event')),
  status text not null default 'queued'
    check (status in ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
  input jsonb not null default '{}'::jsonb,
  output jsonb,
  error_message text,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  unique (id, organization_id),
  foreign key (rule_id, organization_id)
    references public.automation_rules(id, organization_id) on delete cascade
);

create index automation_runs_org_time_idx
  on public.automation_runs(organization_id, created_at desc);
create index automation_runs_rule_idx
  on public.automation_runs(rule_id, created_at desc);

create table public.background_jobs (
  id bigint generated always as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  rule_id uuid not null,
  run_id uuid not null unique,
  job_type text not null default 'notification' check (job_type = 'notification'),
  payload jsonb not null default '{}'::jsonb check (jsonb_typeof(payload) = 'object'),
  status text not null default 'queued'
    check (status in ('queued', 'running', 'succeeded', 'failed', 'dead')),
  run_at timestamptz not null default now(),
  priority smallint not null default 100 check (priority between 0 and 1000),
  attempts integer not null default 0 check (attempts >= 0),
  max_attempts integer not null default 5 check (max_attempts between 1 and 20),
  locked_at timestamptz,
  locked_by text,
  last_error text,
  idempotency_key text not null unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  foreign key (rule_id, organization_id)
    references public.automation_rules(id, organization_id) on delete cascade,
  foreign key (run_id, organization_id)
    references public.automation_runs(id, organization_id) on delete cascade
);

create index background_jobs_claim_idx
  on public.background_jobs(status, run_at, priority, id) where status in ('queued', 'running');
create index background_jobs_org_idx on public.background_jobs(organization_id, created_at desc);

alter table public.tenant_configurations enable row level security;
alter table public.platform_subscriptions enable row level security;
alter table public.subscription_events enable row level security;
alter table public.support_cases enable row level security;
alter table public.knowledge_articles enable row level security;
alter table public.integration_connections enable row level security;
alter table public.integration_events enable row level security;
alter table public.automation_rules enable row level security;
alter table public.automation_schedules enable row level security;
alter table public.automation_runs enable row level security;
alter table public.background_jobs enable row level security;

create policy tenant_configurations_select on public.tenant_configurations for select to authenticated
  using ((select public.is_member_of(organization_id)) or (select public.is_himark_admin()));
create policy tenant_configurations_insert on public.tenant_configurations for insert to authenticated
  with check ((select public.is_himark_admin()));
create policy tenant_configurations_update on public.tenant_configurations for update to authenticated
  using ((select public.is_himark_admin())) with check ((select public.is_himark_admin()));

create policy platform_subscriptions_select on public.platform_subscriptions for select to authenticated
  using ((select public.has_role(organization_id, array['owner','admin'])) or (select public.is_himark_admin()));
create policy platform_subscriptions_insert on public.platform_subscriptions for insert to authenticated
  with check ((select public.is_himark_admin()));
create policy platform_subscriptions_update on public.platform_subscriptions for update to authenticated
  using ((select public.is_himark_admin())) with check ((select public.is_himark_admin()));
create policy subscription_events_select on public.subscription_events for select to authenticated
  using ((select public.has_role(organization_id, array['owner','admin'])) or (select public.is_himark_admin()));

create policy support_cases_internal_select on public.support_cases for select to authenticated
  using ((select public.is_himark_admin()));
create policy support_cases_internal_insert on public.support_cases for insert to authenticated
  with check ((select public.is_himark_admin()));
create policy support_cases_internal_update on public.support_cases for update to authenticated
  using ((select public.is_himark_admin())) with check ((select public.is_himark_admin()));
create policy support_tickets_internal_select on public.support_tickets for select to authenticated
  using ((select public.is_himark_admin()));
create policy support_tickets_internal_update on public.support_tickets for update to authenticated
  using ((select public.is_himark_admin())) with check ((select public.is_himark_admin()));
create policy organizations_internal_select on public.organizations for select to authenticated
  using ((select public.is_himark_admin()));

create policy knowledge_articles_select on public.knowledge_articles for select to authenticated
  using (
    (select public.is_himark_admin())
    or ((select public.is_member_of(organization_id)) and visibility = 'organization' and status = 'published')
    or ((select public.has_role(organization_id, array['owner','admin'])) and visibility = 'organization')
  );
create policy knowledge_articles_insert on public.knowledge_articles for insert to authenticated
  with check (
    (select public.is_himark_admin())
    or ((select public.has_role(organization_id, array['owner','admin'])) and visibility = 'organization')
  );
create policy knowledge_articles_update on public.knowledge_articles for update to authenticated
  using (
    (select public.is_himark_admin())
    or ((select public.has_role(organization_id, array['owner','admin'])) and visibility = 'organization')
  )
  with check (
    (select public.is_himark_admin())
    or ((select public.has_role(organization_id, array['owner','admin'])) and visibility = 'organization')
  );

create policy integration_connections_select on public.integration_connections for select to authenticated
  using ((select public.is_member_of(organization_id)));
create policy integration_connections_insert on public.integration_connections for insert to authenticated
  with check ((select public.has_role(organization_id, array['owner','admin'])));
create policy integration_connections_update on public.integration_connections for update to authenticated
  using ((select public.has_role(organization_id, array['owner','admin'])))
  with check ((select public.has_role(organization_id, array['owner','admin'])));
create policy integration_connections_delete on public.integration_connections for delete to authenticated
  using ((select public.has_role(organization_id, array['owner','admin'])));

create policy integration_events_select on public.integration_events for select to authenticated
  using ((select public.is_member_of(organization_id)));

create policy automation_rules_select on public.automation_rules for select to authenticated
  using ((select public.is_member_of(organization_id)));
create policy automation_rules_insert on public.automation_rules for insert to authenticated
  with check ((select public.has_role(organization_id, array['owner','admin'])));
create policy automation_rules_update on public.automation_rules for update to authenticated
  using ((select public.has_role(organization_id, array['owner','admin'])))
  with check ((select public.has_role(organization_id, array['owner','admin'])));
create policy automation_rules_delete on public.automation_rules for delete to authenticated
  using ((select public.has_role(organization_id, array['owner','admin'])));

create policy automation_schedules_select on public.automation_schedules for select to authenticated
  using ((select public.is_member_of(organization_id)));
create policy automation_schedules_insert on public.automation_schedules for insert to authenticated
  with check ((select public.has_role(organization_id, array['owner','admin'])));
create policy automation_schedules_update on public.automation_schedules for update to authenticated
  using ((select public.has_role(organization_id, array['owner','admin'])))
  with check ((select public.has_role(organization_id, array['owner','admin'])));
create policy automation_schedules_delete on public.automation_schedules for delete to authenticated
  using ((select public.has_role(organization_id, array['owner','admin'])));

create policy automation_runs_select on public.automation_runs for select to authenticated
  using ((select public.is_member_of(organization_id)));

revoke all on public.tenant_configurations, public.platform_subscriptions,
  public.subscription_events, public.support_cases, public.knowledge_articles,
  public.integration_connections, public.integration_events, public.automation_rules,
  public.automation_schedules, public.automation_runs, public.background_jobs from anon;

grant select, insert, update on public.tenant_configurations to authenticated;
grant select, insert, update on public.platform_subscriptions to authenticated;
grant select on public.subscription_events to authenticated;
grant select, insert, update on public.support_cases to authenticated;
grant select, insert, update on public.knowledge_articles to authenticated;
grant select, insert, update, delete on public.integration_connections to authenticated;
grant select on public.integration_events to authenticated;
grant select, insert, update, delete on public.automation_rules to authenticated;
grant select, insert, update, delete on public.automation_schedules to authenticated;
grant select on public.automation_runs to authenticated;
grant usage, select on sequence public.subscription_events_id_seq to authenticated;

create trigger tenant_configurations_set_updated_at before update on public.tenant_configurations
  for each row execute function public.set_updated_at();
create trigger platform_subscriptions_set_updated_at before update on public.platform_subscriptions
  for each row execute function public.set_updated_at();
create trigger support_cases_set_updated_at before update on public.support_cases
  for each row execute function public.set_updated_at();
create trigger knowledge_articles_set_updated_at before update on public.knowledge_articles
  for each row execute function public.set_updated_at();
create trigger integration_connections_set_updated_at before update on public.integration_connections
  for each row execute function public.set_updated_at();
create trigger automation_rules_set_updated_at before update on public.automation_rules
  for each row execute function public.set_updated_at();
create trigger automation_schedules_set_updated_at before update on public.automation_schedules
  for each row execute function public.set_updated_at();
create trigger background_jobs_set_updated_at before update on public.background_jobs
  for each row execute function public.set_updated_at();

create trigger platform_subscriptions_audit after insert or update or delete on public.platform_subscriptions
  for each row execute function public.record_audit_event();
create trigger support_cases_audit after insert or update or delete on public.support_cases
  for each row execute function public.record_audit_event();
create trigger knowledge_articles_audit after insert or update or delete on public.knowledge_articles
  for each row execute function public.record_audit_event();
create trigger integration_connections_audit after insert or update or delete on public.integration_connections
  for each row execute function public.record_audit_event();
create trigger automation_rules_audit after insert or update or delete on public.automation_rules
  for each row execute function public.record_audit_event();
create trigger automation_schedules_audit after insert or update or delete on public.automation_schedules
  for each row execute function public.record_audit_event();

create or replace function private.index_platform_record_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  payload jsonb;
  target_org uuid;
  target_id uuid;
  target_title text;
  target_subtitle text;
  target_href text;
  should_remove boolean := false;
begin
  if auth.uid() is null and current_user not in ('postgres', 'service_role') then
    raise insufficient_privilege using message = 'An authenticated database role is required';
  end if;

  payload := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  target_org := (payload ->> 'organization_id')::uuid;
  target_id := (payload ->> 'id')::uuid;

  case tg_table_name
    when 'knowledge_articles' then
      target_title := payload ->> 'title';
      target_subtitle := concat_ws(' · ', payload ->> 'category', payload ->> 'status', payload ->> 'summary');
      target_href := '/knowledge/' || target_id;
      should_remove := payload ->> 'status' = 'archived' or payload ->> 'visibility' = 'internal';
    when 'integration_connections' then
      target_title := payload ->> 'name';
      target_subtitle := concat_ws(' · ', payload ->> 'provider', payload ->> 'status', payload ->> 'event_key');
      target_href := '/settings/integrations/' || target_id;
    when 'automation_rules' then
      target_title := payload ->> 'name';
      target_subtitle := concat_ws(' · ', payload ->> 'trigger_type', payload ->> 'status', payload ->> 'description');
      target_href := '/settings/automations/' || target_id;
    else
      raise exception 'Unsupported platform search resource: %', tg_table_name;
  end case;

  if tg_op = 'DELETE' or should_remove then
    delete from public.record_index
    where organization_id = target_org and resource = tg_table_name and record_id = target_id;
  else
    insert into public.record_index(organization_id, resource, record_id, title, subtitle, href, updated_at)
    values (
      target_org, tg_table_name, target_id,
      coalesce(target_title, 'Untitled record'), coalesce(target_subtitle, ''), target_href,
      coalesce((payload ->> 'updated_at')::timestamptz, (payload ->> 'created_at')::timestamptz, now())
    )
    on conflict (organization_id, resource, record_id) do update set
      title = excluded.title,
      subtitle = excluded.subtitle,
      href = excluded.href,
      updated_at = excluded.updated_at;
  end if;

  if exists (select 1 from public.organizations where id = target_org) then
    insert into public.record_change_events(organization_id, resource, record_id, operation, actor_id)
    values (target_org, tg_table_name, target_id, tg_op, auth.uid());
  end if;
  if tg_op = 'DELETE' then return old; end if;
  return new;
end;
$$;

revoke all on function private.index_platform_record_change() from public, anon, authenticated, service_role;
create trigger knowledge_articles_search_realtime after insert or update or delete on public.knowledge_articles
  for each row execute function private.index_platform_record_change();
create trigger integration_connections_search_realtime after insert or update or delete on public.integration_connections
  for each row execute function private.index_platform_record_change();
create trigger automation_rules_search_realtime after insert or update or delete on public.automation_rules
  for each row execute function private.index_platform_record_change();

create or replace function private.record_subscription_event()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  event_action text;
begin
  if tg_op = 'INSERT' then
    event_action := 'created';
  elsif new.status = 'paused' and old.status <> 'paused' then
    event_action := 'paused';
  elsif new.status = 'active' and old.status = 'paused' then
    event_action := 'resumed';
  elsif new.status = 'cancelled' and old.status <> 'cancelled' then
    event_action := 'cancelled';
  else
    event_action := 'updated';
  end if;

  insert into public.subscription_events(
    organization_id, subscription_id, actor_id, action, old_value, new_value
  ) values (
    new.organization_id, new.id, auth.uid(), event_action,
    case when tg_op = 'UPDATE' then to_jsonb(old) else null end,
    to_jsonb(new)
  );
  return new;
end;
$$;

revoke all on function private.record_subscription_event() from public, anon, authenticated, service_role;
create trigger platform_subscriptions_history after insert or update on public.platform_subscriptions
  for each row execute function private.record_subscription_event();

create or replace function public.rotate_integration_secret(p_connection_id uuid)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_org uuid;
  generated_secret text;
begin
  select organization_id into target_org
  from public.integration_connections
  where id = p_connection_id;

  if target_org is null
     or not public.has_role(target_org, array['owner','admin']) then
    raise insufficient_privilege using message = 'Integration administration is required';
  end if;

  generated_secret := encode(extensions.gen_random_bytes(24), 'hex');
  insert into private.integration_secrets(connection_id, secret_hash, rotated_at)
  values (p_connection_id, extensions.digest(generated_secret, 'sha256'), now())
  on conflict (connection_id) do update
    set secret_hash = excluded.secret_hash, rotated_at = excluded.rotated_at;

  update public.integration_connections
  set secret_hint = right(generated_secret, 6), status = 'connected', last_error = null
  where id = p_connection_id;

  return generated_secret;
end;
$$;

revoke all on function public.rotate_integration_secret(uuid) from public, anon;
grant execute on function public.rotate_integration_secret(uuid) to authenticated;

create or replace function public.ingest_integration_event(
  p_connection_id uuid,
  p_secret text,
  p_event_key text,
  p_external_id text default null,
  p_payload jsonb default '{}'::jsonb
)
returns table(event_id bigint, run_ids uuid[])
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_connection public.integration_connections%rowtype;
  target_event_id bigint;
  target_run_id uuid;
  collected_run_ids uuid[] := '{}';
  target_rule record;
begin
  if p_secret is null or length(p_secret) < 16 or length(p_secret) > 512
     or p_event_key is null or p_event_key !~ '^[a-z0-9][a-z0-9._-]{1,79}$'
     or jsonb_typeof(p_payload) <> 'object'
     or octet_length(p_payload::text) > 65536 then
    raise insufficient_privilege using message = 'Integration credential rejected';
  end if;

  select c.* into target_connection
  from public.integration_connections c
  join private.integration_secrets s on s.connection_id = c.id
  where c.id = p_connection_id
    and c.status = 'connected'
    and s.secret_hash = extensions.digest(p_secret, 'sha256');

  if target_connection.id is null
     or (target_connection.event_key <> '*' and target_connection.event_key <> p_event_key) then
    raise insufficient_privilege using message = 'Integration credential rejected';
  end if;

  insert into public.integration_events(
    organization_id, connection_id, event_key, external_id, payload
  ) values (
    target_connection.organization_id, target_connection.id, p_event_key,
    nullif(trim(p_external_id), ''), p_payload
  )
  on conflict (connection_id, external_id) where external_id is not null do nothing
  returning id into target_event_id;

  if target_event_id is null then
    select id into target_event_id
    from public.integration_events
    where connection_id = target_connection.id and external_id = p_external_id;
    return query select target_event_id, collected_run_ids;
    return;
  end if;

  update public.integration_connections
  set last_event_at = now(), last_error = null
  where id = target_connection.id;

  for target_rule in
    select r.id, r.organization_id, r.action_config
    from public.automation_rules r
    where r.organization_id = target_connection.organization_id
      and r.integration_connection_id = target_connection.id
      and r.trigger_type = 'integration_event'
      and r.status = 'active'
      and coalesce(r.trigger_config ->> 'event_key', '*') in ('*', p_event_key)
  loop
    insert into public.automation_runs(
      organization_id, rule_id, integration_event_id, trigger_type, input
    ) values (
      target_rule.organization_id, target_rule.id, target_event_id,
      'integration_event', p_payload
    ) returning id into target_run_id;

    insert into public.background_jobs(
      organization_id, rule_id, run_id, payload, idempotency_key
    ) values (
      target_rule.organization_id, target_rule.id, target_run_id,
      target_rule.action_config,
      'event:' || target_event_id || ':rule:' || target_rule.id
    );
    collected_run_ids := array_append(collected_run_ids, target_run_id);
  end loop;

  update public.integration_events
  set status = case when cardinality(collected_run_ids) > 0 then 'processed' else 'ignored' end
  where id = target_event_id;

  return query select target_event_id, collected_run_ids;
end;
$$;

revoke all on function public.ingest_integration_event(uuid,text,text,text,jsonb) from public;
grant execute on function public.ingest_integration_event(uuid,text,text,text,jsonb) to anon, authenticated, service_role;

create or replace function public.enqueue_automation_rule(
  p_rule_id uuid,
  p_input jsonb default '{}'::jsonb
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_rule public.automation_rules%rowtype;
  target_run_id uuid;
begin
  select * into target_rule from public.automation_rules where id = p_rule_id;
  if target_rule.id is null
     or not public.has_role(target_rule.organization_id, array['owner','admin']) then
    raise insufficient_privilege using message = 'Automation administration is required';
  end if;
  if target_rule.status <> 'active' then
    raise check_violation using message = 'Only active automations can run';
  end if;

  insert into public.automation_runs(organization_id, rule_id, trigger_type, input)
  values (target_rule.organization_id, target_rule.id, 'manual', coalesce(p_input, '{}'::jsonb))
  returning id into target_run_id;

  insert into public.background_jobs(
    organization_id, rule_id, run_id, payload, idempotency_key
  ) values (
    target_rule.organization_id, target_rule.id, target_run_id,
    target_rule.action_config, 'manual:' || target_run_id
  );
  return target_run_id;
end;
$$;

revoke all on function public.enqueue_automation_rule(uuid,jsonb) from public, anon;
grant execute on function public.enqueue_automation_rule(uuid,jsonb) to authenticated;

create or replace function private.enqueue_due_automation_schedules()
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  target record;
  target_run_id uuid;
  queued_count integer := 0;
begin
  if not pg_try_advisory_xact_lock(hashtext('unison:enqueue-due-automation-schedules')) then
    return 0;
  end if;

  for target in
    select s.id as schedule_id, s.organization_id, s.rule_id,
      s.interval_minutes, s.next_run_at, r.action_config
    from public.automation_schedules s
    join public.automation_rules r
      on r.id = s.rule_id and r.organization_id = s.organization_id
    where s.enabled and s.next_run_at <= now() and r.status = 'active'
    order by s.next_run_at
    limit 100
    for update of s skip locked
  loop
    insert into public.automation_runs(organization_id, rule_id, trigger_type, input)
    values (
      target.organization_id, target.rule_id, 'schedule',
      jsonb_build_object('scheduled_for', target.next_run_at)
    ) returning id into target_run_id;

    insert into public.background_jobs(
      organization_id, rule_id, run_id, payload, idempotency_key
    ) values (
      target.organization_id, target.rule_id, target_run_id, target.action_config,
      'schedule:' || target.schedule_id || ':' || extract(epoch from target.next_run_at)::bigint
    ) on conflict (idempotency_key) do nothing;

    update public.automation_schedules
    set last_enqueued_at = now(),
        next_run_at = greatest(now(), target.next_run_at) + make_interval(mins => target.interval_minutes)
    where id = target.schedule_id;
    queued_count := queued_count + 1;
  end loop;
  return queued_count;
end;
$$;

revoke all on function private.enqueue_due_automation_schedules() from public, anon, authenticated, service_role;

create or replace function private.process_background_jobs(p_limit integer default 50)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  target public.background_jobs%rowtype;
  processed_count integer := 0;
  notification_title text;
  notification_body text;
  notification_href text;
  notification_category text;
begin
  for target in
    select *
    from public.background_jobs
    where (
      (status = 'queued' and run_at <= now())
      or (status = 'running' and locked_at < now() - interval '10 minutes')
    )
    order by priority, run_at, id
    limit least(greatest(p_limit, 1), 100)
    for update skip locked
  loop
    begin
      update public.background_jobs
      set status = 'running', locked_at = now(), locked_by = 'supabase-cron',
          attempts = attempts + 1, last_error = null
      where id = target.id;

      update public.automation_runs
      set status = 'running', started_at = coalesce(started_at, now()), error_message = null
      where id = target.run_id;

      notification_title := coalesce(nullif(trim(target.payload ->> 'title'), ''), 'Automation completed');
      notification_body := nullif(trim(target.payload ->> 'body'), '');
      notification_href := nullif(trim(target.payload ->> 'href'), '');
      notification_category := case
        when target.payload ->> 'category' in ('System','Delivery','Operations','Commercial','Finance','Support','Documents','Import')
          then target.payload ->> 'category'
        else 'System'
      end;
      if notification_href is not null and (notification_href not like '/%' or notification_href like '//%') then
        notification_href := null;
      end if;

      insert into public.notifications(organization_id, user_id, title, body, category, href)
      select target.organization_id, m.user_id, notification_title, notification_body, notification_category, notification_href
      from public.memberships m
      where m.organization_id = target.organization_id and m.status = 'active';

      update public.background_jobs
      set status = 'succeeded', locked_at = null, locked_by = null
      where id = target.id;
      update public.automation_runs
      set status = 'succeeded', output = jsonb_build_object('notified', true), completed_at = now()
      where id = target.run_id;
      update public.automation_rules
      set run_count = run_count + 1, last_run_at = now()
      where id = target.rule_id;
      processed_count := processed_count + 1;
    exception when others then
      update public.background_jobs
      set status = case when attempts >= max_attempts then 'dead' else 'queued' end,
          run_at = now() + make_interval(mins => least(60, greatest(1, attempts * attempts))),
          locked_at = null, locked_by = null, last_error = left(sqlerrm, 2000)
      where id = target.id;
      update public.automation_runs
      set status = case
            when (select attempts >= max_attempts from public.background_jobs where id = target.id) then 'failed'
            else 'queued'
          end,
          error_message = left(sqlerrm, 2000),
          completed_at = case
            when (select attempts >= max_attempts from public.background_jobs where id = target.id) then now()
            else null
          end
      where id = target.run_id;
    end;
  end loop;
  return processed_count;
end;
$$;

revoke all on function private.process_background_jobs(integer) from public, anon, authenticated, service_role;

-- Schedule both stages independently. Direct cron.job writes are intentionally
-- avoided; current Supabase only supports the cron management functions.
create extension if not exists pg_cron;
do $$
begin
  if not exists (select 1 from cron.job where jobname = 'unison-enqueue-automations') then
    perform cron.schedule(
      'unison-enqueue-automations', '* * * * *',
      'select private.enqueue_due_automation_schedules();'
    );
  end if;
  if not exists (select 1 from cron.job where jobname = 'unison-process-automation-jobs') then
    perform cron.schedule(
      'unison-process-automation-jobs', '* * * * *',
      'select private.process_background_jobs(50);'
    );
  end if;
end;
$$;

insert into public.tenant_configurations(organization_id)
select id from public.organizations where tier = 'strategic-enterprise'
on conflict (organization_id) do nothing;
